import { describe, expect, it } from '@jest/globals';
import { applyMessagingGuidedPersonaliseAnswer, nextMessagingGuidedPersonaliseQuestion } from './messaging-quote-guided-personalise';
import type { MessagingQuoteDraftProgress } from './messaging-quote-draft';

function draft(primary = 'Regular Home Cleaning'): MessagingQuoteDraftProgress { return { request: { primaryService: { websiteValue: primary, canonicalService: primary }, frequency: 'ONE_TIME', homeCondition: 'STANDARD' } }; }

describe('guided Messaging service personalisation', () => {
  it('offers laundry and ironing only for eligible primary services', () => { expect(nextMessagingGuidedPersonaliseQuestion(draft())?.text).toContain('12. Laundry'); expect(nextMessagingGuidedPersonaliseQuestion(draft('Move-In Cleaning'))?.text).not.toContain('12. Laundry'); });
  it('accepts bounded add-on selections and keeps structured laundry out of addOns', () => { const result = applyMessagingGuidedPersonaliseAnswer(draft(), '1,10,12,13'); expect(result.kind).toBe('ACCEPTED'); if (result.kind !== 'ACCEPTED') return; expect(result.patch.request?.addOns).toEqual([{ websiteValue: 'Inside oven', canonicalService: 'Inside Oven Cleaning', quantity: 1 }, { websiteValue: 'Extra refrigerator', canonicalService: 'Extra Refrigerator', quantity: 0 }]); expect(result.patch.request?.laundry).toEqual({ laundryLoads: 0, ironingLoads: 0 }); });
  it('rejects unsupported or ineligible laundry selections', () => { expect(applyMessagingGuidedPersonaliseAnswer(draft(), '99').kind).toBe('INVALID'); expect(applyMessagingGuidedPersonaliseAnswer(draft('Move-In Cleaning'), '12').kind).toBe('INVALID'); });
  it('collects quantities for quantity-based add-ons', () => { const withAddOns: MessagingQuoteDraftProgress = { ...draft(), request: { ...draft().request, addOns: [{ websiteValue: 'Extra refrigerator', canonicalService: 'Extra Refrigerator', quantity: 0 }, { websiteValue: 'Balcony / Patio Cleaning', canonicalService: 'Balcony / Patio Cleaning', quantity: 0 }] } }; expect(nextMessagingGuidedPersonaliseQuestion(withAddOns)?.id).toBe('EXTRA_REFRIGERATOR_QUANTITY'); const fridge = applyMessagingGuidedPersonaliseAnswer(withAddOns, '2'); expect(fridge.kind).toBe('ACCEPTED'); if (fridge.kind !== 'ACCEPTED') return; expect(fridge.patch.request?.addOns?.[0]?.quantity).toBe(2); });
  it('collects eco-friendly preference as an explicit boolean', () => { const ready: MessagingQuoteDraftProgress = { ...draft(), request: { ...draft().request, addOns: [] } }; expect(nextMessagingGuidedPersonaliseQuestion(ready)?.id).toBe('ECO_FRIENDLY_PRODUCTS'); expect(applyMessagingGuidedPersonaliseAnswer(ready, '1')).toEqual({ kind: 'ACCEPTED', patch: { request: { ecoFriendlyProducts: true } } }); });
  it('collects laundry facilities and load quantities deterministically', () => { const selected: MessagingQuoteDraftProgress = { ...draft(), request: { ...draft().request, addOns: [], ecoFriendlyProducts: false, laundry: { laundryLoads: 0, ironingLoads: 0 } } }; expect(nextMessagingGuidedPersonaliseQuestion(selected)?.id).toBe('LAUNDRY_FACILITIES'); const facilities = applyMessagingGuidedPersonaliseAnswer(selected, '1'); expect(facilities.kind).toBe('ACCEPTED'); if (facilities.kind !== 'ACCEPTED') return; const withFacilities: MessagingQuoteDraftProgress = { ...selected, request: { ...selected.request, laundry: facilities.patch.request?.laundry } }; expect(nextMessagingGuidedPersonaliseQuestion(withFacilities)?.id).toBe('LAUNDRY_LOADS'); const loads = applyMessagingGuidedPersonaliseAnswer(withFacilities, '2'); expect(loads.kind).toBe('ACCEPTED'); if (loads.kind !== 'ACCEPTED') return; const withLaundryLoads: MessagingQuoteDraftProgress = { ...withFacilities, request: { ...withFacilities.request, laundry: loads.patch.request?.laundry } }; expect(nextMessagingGuidedPersonaliseQuestion(withLaundryLoads)?.id).toBe('IRONING_LOADS'); });
  it('continues into Preferred Visit after personalisation is complete', () => { const complete: MessagingQuoteDraftProgress = { ...draft(), request: { ...draft().request, addOns: [], ecoFriendlyProducts: false } }; expect(nextMessagingGuidedPersonaliseQuestion(complete)?.id).toBe('PREFERRED_DATE'); expect(applyMessagingGuidedPersonaliseAnswer(complete, '2026-08-30')).toEqual({ kind:'ACCEPTED', patch:{ visit:{ preferredDate:'2026-08-30' } } }); });
});
