import type {
  MessagingChannel,
  NormalizedInboundMessagingEvent,
  OutboundMessagingCommand,
  OutboundMessagingResult,
} from './messaging-contract';

export interface MessagingWebhookContext {
  /** ISO-8601 timestamp generated by HestivaOS when the webhook request arrived. */
  receivedAt: string;
  /** Provider-supplied headers required for later authenticity verification. */
  headers: Readonly<Record<string, string | string[] | undefined>>;
}

export interface MessagingProviderAdapter {
  readonly channel: MessagingChannel;
  readonly provider: string;

  /**
   * Verify and normalize one raw provider webhook payload.
   *
   * Implementations must fail closed when provider authenticity cannot be
   * established. One webhook may normalize to zero, one, or many events.
   */
  normalizeInboundWebhook(
    payload: unknown,
    context: MessagingWebhookContext,
  ): Promise<ReadonlyArray<NormalizedInboundMessagingEvent>>;

  /**
   * Submit an already-authorized outbound command to the provider.
   * Business authorization, pricing, availability, and booking decisions do
   * not belong in an adapter.
   */
  send(command: OutboundMessagingCommand): Promise<OutboundMessagingResult>;
}
