import type {
  MessagingChannel,
  NormalizedInboundMessagingEvent,
  OutboundMessagingCommand,
  OutboundMessagingResult,
} from './messaging-contract';

export class MessagingProviderOutcomeUnknownError extends Error {
  constructor(message = 'The provider send outcome could not be established safely.') {
    super(message);
    this.name = 'MessagingProviderOutcomeUnknownError';
  }
}

export interface MessagingWebhookContext {
  /** ISO-8601 timestamp generated by HestivaOS when the webhook request arrived. */
  receivedAt: string;
  /** Provider-supplied headers required for authenticity verification. */
  headers: Readonly<Record<string, string | string[] | undefined>>;
  /**
   * Exact request bytes as received from the provider. Required by providers
   * whose authenticity signature covers the raw HTTP body (for example Meta).
   * Never persist this value as normal messaging history.
   */
  rawBody?: Uint8Array;
}

export interface MessagingProviderAdapter {
  readonly channel: MessagingChannel;
  readonly provider: string;

  /**
   * Verify and normalize one raw provider webhook payload.
   *
   * Implementations must fail closed when provider authenticity cannot be
   * established. One webhook may normalize to zero, one, or many events.
   */
  normalizeInboundWebhook(
    payload: unknown,
    context: MessagingWebhookContext,
  ): Promise<ReadonlyArray<NormalizedInboundMessagingEvent>>;

  /**
   * Submit an already-authorized outbound command to the provider.
   * Business authorization, pricing, availability, and booking decisions do
   * not belong in an adapter.
   */
  send(command: OutboundMessagingCommand): Promise<OutboundMessagingResult>;
}
