import { BadRequestException, ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, TemporaryAccessCredentialEventType, TemporaryAccessCredentialReviewStatus, TemporaryAccessCredentialType, WorkOrderAccessReadiness, WorkOrderActivityType } from '@prisma/client';
import { PrismaService } from '../prisma.service';
import { decryptCredential, encryptCredential } from './temporary-access-crypto';

export type CreateTemporaryCredentialInput = { requestId: string; type: TemporaryAccessCredentialType; protectedText?: string; attachmentStoragePath?: string; attachmentFileName?: string; attachmentMediaType?: string; derivedMetadata?: Record<string, string>; validFrom?: string; expiresAt?: string; singleUse?: boolean; sourceMessageId?: string };
export type ReviewTemporaryCredentialInput = { decision: 'ACCEPT'|'REJECT'; reason?: string };
const TYPES = new Set(Object.values(TemporaryAccessCredentialType));
const projection = { id:true, workOrderId:true, sourceMessageId:true, type:true, attachmentFileName:true, attachmentMediaType:true, validFrom:true, expiresAt:true, singleUse:true, revokedAt:true, reviewStatus:true, createdAt:true, updatedAt:true, createdBy:{select:{id:true,firstName:true,lastName:true,displayName:true}}, events:{select:{id:true,type:true,reason:true,createdAt:true,actor:{select:{id:true,firstName:true,lastName:true,displayName:true}}},orderBy:{createdAt:'asc' as const}} };

@Injectable()
export class WorkOrderTemporaryAccessCredentialsService {
  constructor(private readonly prisma: PrismaService) {}
  async list(workOrderId:string, actorId:string) { await this.expire(workOrderId,actorId); await this.assertWorkOrder(workOrderId); return this.prisma.workOrderTemporaryAccessCredential.findMany({where:{workOrderId},select:projection,orderBy:{createdAt:'desc'}}); }
  async create(workOrderId:string,input:CreateTemporaryCredentialInput,actorId:string) {
    if(!TYPES.has(input.type)) throw new BadRequestException('Select a valid credential type.');
    if(!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(input.requestId))throw new BadRequestException('requestId must be a UUID.');
    const text=input.protectedText?.trim(); const path=input.attachmentStoragePath?.trim();
    if(!text&&!path) throw new BadRequestException('Protected text or a private attachment is required.');
    if(text&&text.length>2000) throw new BadRequestException('Protected text must be 2,000 characters or fewer.');
    if(path&&!path.startsWith(`temporary-access/${workOrderId}/`)) throw new BadRequestException('Private attachment path must be scoped to this Work Order.');
    if(path&&!input.attachmentFileName?.trim()) throw new BadRequestException('Original attachment filename is required.');
    const validFrom=this.date(input.validFrom,'validFrom'); const expiresAt=this.date(input.expiresAt,'expiresAt');
    if(validFrom&&expiresAt&&expiresAt<=validFrom) throw new BadRequestException('Expiry must be after validity begins.');
    return this.prisma.$transaction(async tx=>{
      await this.assertWorkOrder(workOrderId,tx);
      const replay=await tx.workOrderTemporaryAccessCredential.findUnique({where:{requestId:input.requestId},select:projection});
      if(replay){if(replay.workOrderId!==workOrderId)throw new ConflictException('Request identity is already bound to another Work Order.');return replay;}
      if(input.sourceMessageId&&!await tx.messagingMessage.findFirst({where:{id:input.sourceMessageId,responseRecovery:{workOrderId}},select:{id:true}}))throw new ConflictException('Source message is not linked to this Work Order recovery.');
      const credential=await tx.workOrderTemporaryAccessCredential.create({data:{workOrderId,type:input.type,secretValue:text?encryptCredential(text):null,attachmentStoragePath:path||null,attachmentFileName:input.attachmentFileName?.trim()||null,attachmentMediaType:input.attachmentMediaType?.trim()||null,derivedMetadata:input.derivedMetadata??undefined,validFrom,expiresAt,singleUse:input.singleUse??false,createdById:actorId,requestId:input.requestId,sourceMessageId:input.sourceMessageId},select:projection});
      await tx.workOrderTemporaryAccessCredentialEvent.create({data:{credentialId:credential.id,type:TemporaryAccessCredentialEventType.CREATED,actorId}});
      await this.readiness(tx,workOrderId,WorkOrderAccessReadiness.NEEDS_REVIEW,actorId);
      return credential;
    },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
  }
  async reveal(workOrderId:string,id:string,actorId:string){await this.expire(workOrderId,actorId);return this.prisma.$transaction(async tx=>{const item=await tx.workOrderTemporaryAccessCredential.findFirst({where:{id,workOrderId}});if(!item)throw new NotFoundException('Temporary credential not found.');if(item.reviewStatus!==TemporaryAccessCredentialReviewStatus.ACCEPTED||item.revokedAt||item.expiresAt&&item.expiresAt<=new Date()||item.validFrom&&item.validFrom>new Date())throw new ConflictException('Temporary credential is not currently operationally usable.');await tx.workOrderTemporaryAccessCredentialEvent.create({data:{credentialId:id,type:TemporaryAccessCredentialEventType.VIEWED,actorId}});return {id:item.id,protectedText:item.secretValue?decryptCredential(item.secretValue):null,attachmentStoragePath:item.attachmentStoragePath};});}
  async review(workOrderId:string,id:string,input:ReviewTemporaryCredentialInput,actorId:string){if(!['ACCEPT','REJECT'].includes(input.decision))throw new BadRequestException('Select ACCEPT or REJECT.');return this.prisma.$transaction(async tx=>{const item=await tx.workOrderTemporaryAccessCredential.findFirst({where:{id,workOrderId}});if(!item)throw new NotFoundException('Temporary credential not found.');if(item.reviewStatus!==TemporaryAccessCredentialReviewStatus.PENDING_REVIEW)throw new ConflictException('Only a pending credential can be reviewed.');const accepted=input.decision==='ACCEPT';if(accepted&&item.expiresAt&&item.expiresAt<=new Date())throw new ConflictException('An expired credential cannot be accepted.');const status=accepted?TemporaryAccessCredentialReviewStatus.ACCEPTED:TemporaryAccessCredentialReviewStatus.REJECTED;const updated=await tx.workOrderTemporaryAccessCredential.update({where:{id},data:{reviewStatus:status},select:projection});await tx.workOrderTemporaryAccessCredentialEvent.create({data:{credentialId:id,type:accepted?TemporaryAccessCredentialEventType.ACCEPTED:TemporaryAccessCredentialEventType.REJECTED,actorId,reason:input.reason?.trim()||null}});await this.readiness(tx,workOrderId,accepted?WorkOrderAccessReadiness.RECEIVED:await this.remainingState(tx,workOrderId),actorId);return updated;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  async revoke(workOrderId:string,id:string,reason:string|undefined,actorId:string){return this.prisma.$transaction(async tx=>{const item=await tx.workOrderTemporaryAccessCredential.findFirst({where:{id,workOrderId}});if(!item)throw new NotFoundException('Temporary credential not found.');if(item.reviewStatus===TemporaryAccessCredentialReviewStatus.REVOKED)return tx.workOrderTemporaryAccessCredential.findUniqueOrThrow({where:{id},select:projection});const updated=await tx.workOrderTemporaryAccessCredential.update({where:{id},data:{reviewStatus:TemporaryAccessCredentialReviewStatus.REVOKED,revokedAt:new Date()},select:projection});await tx.workOrderTemporaryAccessCredentialEvent.create({data:{credentialId:id,type:TemporaryAccessCredentialEventType.REVOKED,actorId,reason:reason?.trim()||null}});await this.readiness(tx,workOrderId,await this.remainingState(tx,workOrderId),actorId);return updated;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
  private async expire(workOrderId:string,actorId:string){const now=new Date();await this.prisma.$transaction(async tx=>{const items=await tx.workOrderTemporaryAccessCredential.findMany({where:{workOrderId,reviewStatus:TemporaryAccessCredentialReviewStatus.ACCEPTED,expiresAt:{lte:now}},select:{id:true}});if(!items.length)return;await tx.workOrderTemporaryAccessCredential.updateMany({where:{id:{in:items.map(x=>x.id)}},data:{reviewStatus:TemporaryAccessCredentialReviewStatus.REVOKED,revokedAt:now}});await tx.workOrderTemporaryAccessCredentialEvent.createMany({data:items.map(x=>({credentialId:x.id,type:TemporaryAccessCredentialEventType.EXPIRED,actorId}))});await this.readiness(tx,workOrderId,await this.remainingState(tx,workOrderId),actorId);});}
  private async remainingState(tx:Prisma.TransactionClient,workOrderId:string){const now=new Date();if(await tx.workOrderTemporaryAccessCredential.findFirst({where:{workOrderId,reviewStatus:TemporaryAccessCredentialReviewStatus.ACCEPTED,revokedAt:null,OR:[{validFrom:null},{validFrom:{lte:now}}],AND:[{OR:[{expiresAt:null},{expiresAt:{gt:now}}]}]},select:{id:true}}))return WorkOrderAccessReadiness.RECEIVED;if(await tx.workOrderTemporaryAccessCredential.findFirst({where:{workOrderId,reviewStatus:TemporaryAccessCredentialReviewStatus.PENDING_REVIEW},select:{id:true}}))return WorkOrderAccessReadiness.NEEDS_REVIEW;return WorkOrderAccessReadiness.EXPIRED;}
  private async readiness(tx:Prisma.TransactionClient,workOrderId:string,state:WorkOrderAccessReadiness,actorId:string){const current=await tx.workOrder.findUnique({where:{id:workOrderId},select:{accessReadiness:true}});if(!current)throw new NotFoundException('Work order not found.');if(current.accessReadiness===state)return;await tx.workOrder.update({where:{id:workOrderId},data:{accessReadiness:state}});await tx.workOrderAccessReadinessEvent.create({data:{workOrderId,previousState:current.accessReadiness,newState:state,actorId}});await tx.workOrderActivity.create({data:{workOrderId,type:WorkOrderActivityType.ACCESS_READINESS_CHANGED,actorId,note:`Access readiness changed from ${current.accessReadiness} to ${state}.`}});}
  private async assertWorkOrder(id:string,tx:Prisma.TransactionClient|PrismaService=this.prisma){if(!await tx.workOrder.findUnique({where:{id},select:{id:true}}))throw new NotFoundException('Work order not found.');}
  private date(value:string|undefined,name:string){if(!value)return undefined;const date=new Date(value);if(Number.isNaN(date.getTime()))throw new BadRequestException(`${name} must be a valid date.`);return date;}
}
