import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash } from 'node:crypto';
import { CompletionCorrectionStatus, Prisma, UserRole, WorkOrderStatus } from '@prisma/client';
import { PrismaService } from '../prisma.service';

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const hash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export type AuthorizeCompletionCorrectionInput={operationId:string;reason:string;sectionIds:string[]};
export type ResubmitCompletionCorrectionInput={operationId:string;fieldCompletedAt:string};

@Injectable()
export class WorkOrderCompletionCorrectionService {
 constructor(private readonly prisma:PrismaService){}
 async authorize(workOrderId:string,input:AuthorizeCompletionCorrectionInput,actor:{id:string;role:UserRole}){
  if(actor.role!==UserRole.ADMIN&&actor.role!==UserRole.SUPERVISOR)throw new ForbiddenException('Only ADMIN or SUPERVISOR may authorize a completion correction.');
  if(!UUID.test(input.operationId))throw new BadRequestException('A valid operation ID is required.');
  const reason=input.reason?.trim(),sectionIds=[...new Set(input.sectionIds??[])];if(!reason||reason.length>1000)throw new BadRequestException('A concise correction reason is required.');if(!sectionIds.length||sectionIds.some(id=>!UUID.test(id)))throw new BadRequestException('Choose at least one valid affected section.');
  const requestHash=hash({workOrderId,reason,sectionIds:[...sectionIds].sort()});
  return this.prisma.$transaction(async tx=>{
   const replay=await tx.workOrderCompletionCorrection.findUnique({where:{operationId:input.operationId}});if(replay){if(replay.requestHash!==requestHash)throw new ConflictException('This operation ID was already used for another correction authorization.');return replay;}
   const job=await tx.workOrder.findUnique({where:{id:workOrderId},select:{status:true,startedScopeRevisionId:true,completionOperationId:true,completedByTechnicianId:true,fieldCompletedAt:true,completionAcceptedAt:true,completionAcknowledgedAt:true,completionAcknowledgedById:true,completionCorrespondenceEligibleAt:true,completionCorrections:{where:{status:{in:[CompletionCorrectionStatus.AUTHORIZED,CompletionCorrectionStatus.IN_PROGRESS]}},select:{id:true}}}});
   if(!job)throw new NotFoundException('Work Order not found.');if(job.status!==WorkOrderStatus.COMPLETED||!job.startedScopeRevisionId||!job.completionOperationId||!job.completedByTechnicianId||!job.fieldCompletedAt||!job.completionAcceptedAt)throw new ConflictException('Only an authoritative completed execution may be corrected.');if(job.completionCorrections.length)throw new ConflictException('This Work Order already has an active correction authorization.');
   const sections=await tx.workOrderExecutionSection.findMany({where:{id:{in:sectionIds},scopeRevisionId:job.startedScopeRevisionId},select:{id:true,currentOutcomeEvent:{select:{technicianId:true}}}});if(sections.length!==sectionIds.length)throw new BadRequestException('Every affected section must belong to the frozen Execution Scope.');const technicianId=sections[0]?.currentOutcomeEvent?.technicianId;if(!technicianId||sections.some(section=>section.currentOutcomeEvent?.technicianId!==technicianId))throw new ConflictException('One authorization may cover only outcomes submitted by the same Technician.');const assignment=await tx.workOrderTechnician.findUnique({where:{workOrderId_technicianId:{workOrderId,technicianId}}});if(!assignment)throw new ConflictException('The submitting Technician is no longer assigned to this Work Order.');
   const correction=await tx.workOrderCompletionCorrection.create({data:{operationId:input.operationId,requestHash,workOrderId,technicianId,authorizedById:actor.id,reason,sectionIds,originalCompletionOperationId:job.completionOperationId,originalCompletedByTechnicianId:job.completedByTechnicianId,originalFieldCompletedAt:job.fieldCompletedAt,originalCompletionAcceptedAt:job.completionAcceptedAt,originalAcknowledgedAt:job.completionAcknowledgedAt,originalAcknowledgedById:job.completionAcknowledgedById,originalCorrespondenceEligibleAt:job.completionCorrespondenceEligibleAt}});
   await tx.workOrderActivity.create({data:{workOrderId,type:'COMPLETION_CORRECTION_AUTHORIZED',actorId:actor.id,newStatus:WorkOrderStatus.COMPLETED,note:`Correction authorized for ${sectionIds.length} frozen-scope section(s): ${reason}`}});return correction;
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
 }
 async list(workOrderId:string){const corrections=await this.prisma.workOrderCompletionCorrection.findMany({where:{workOrderId},orderBy:{createdAt:'asc'},include:{authorizedBy:{select:{id:true,firstName:true,lastName:true}},technician:{select:{id:true,firstName:true,lastName:true}},outcomeEvents:{orderBy:{serverReceivedAt:'asc'},select:{id:true,sectionId:true,outcome:true,reason:true,note:true,fieldRecordedAt:true,serverReceivedAt:true}}}});const sectionIds=[...new Set(corrections.flatMap(item=>item.sectionIds))];const sections=sectionIds.length?await this.prisma.workOrderExecutionSection.findMany({where:{id:{in:sectionIds},scopeRevision:{workOrderId}},select:{id:true,title:true,outcomeEvents:{orderBy:{serverReceivedAt:'asc'},select:{id:true,technicianId:true,outcome:true,reason:true,note:true,fieldRecordedAt:true,serverReceivedAt:true,correctionId:true}}}}):[];return corrections.map(correction=>({...correction,affectedSections:sections.filter(section=>correction.sectionIds.includes(section.id))}));}
 async resubmit(userId:string,workOrderId:string,correctionId:string,input:ResubmitCompletionCorrectionInput){if(!UUID.test(input.operationId))throw new BadRequestException('A valid operation ID is required.');const fieldCompletedAt=new Date(input.fieldCompletedAt);if(!Number.isFinite(fieldCompletedAt.getTime())||fieldCompletedAt.getTime()>Date.now()+300000)throw new BadRequestException('A valid field completion time is required.');const record=await this.prisma.employeeRecord.findFirst({where:{userId,status:'ACTIVE',technician:{status:'ACTIVE'}},select:{technicianId:true}});if(!record?.technicianId)throw new ForbiddenException('Technician access is not available for this account.');const technicianId=record.technicianId;
  return this.prisma.$transaction(async tx=>{const replay=await tx.workOrderCompletionCorrection.findUnique({where:{resubmissionOperationId:input.operationId}});if(replay){if(replay.id!==correctionId||replay.workOrderId!==workOrderId)throw new ConflictException('This resubmission identity belongs to another correction.');return replay;}
   const correction=await tx.workOrderCompletionCorrection.findFirst({where:{id:correctionId,workOrderId,technicianId},include:{workOrder:{select:{status:true,startedScopeRevisionId:true,assignedTechnicians:{select:{technicianId:true}}}}}});if(!correction)throw new NotFoundException('Assigned correction authorization was not found.');if(correction.status!==CompletionCorrectionStatus.IN_PROGRESS)throw new ConflictException('Record at least one authorized correction before resubmitting.');if(correction.workOrder.status!==WorkOrderStatus.COMPLETED||!correction.workOrder.assignedTechnicians.some(item=>item.technicianId===technicianId))throw new ConflictException('Assignment or completion state changed.');
   const sections=await tx.workOrderExecutionSection.findMany({where:{scopeRevisionId:correction.workOrder.startedScopeRevisionId!},select:{title:true,currentOutcome:true,currentOutcomeEvent:{select:{reason:true,note:true}},evidence:{select:{id:true}}}});for(const section of sections){if(section.currentOutcome==='PENDING')throw new ConflictException(`${section.title} still needs an outcome.`);if(section.currentOutcome==='NOT_COMPLETED'&&(!section.currentOutcomeEvent?.reason||!section.currentOutcomeEvent.note?.trim()))throw new ConflictException(`${section.title} needs complete exception details.`);}
   const acceptedAt=new Date();await tx.workOrder.update({where:{id:workOrderId},data:{completionOperationId:input.operationId,completedByTechnicianId:record.technicianId,fieldCompletedAt,completionAcceptedAt:acceptedAt,completedAt:acceptedAt,completionAcknowledgedAt:null,completionAcknowledgedById:null,completionCorrespondenceEligibleAt:null}});const updated=await tx.workOrderCompletionCorrection.update({where:{id:correctionId},data:{status:'RESUBMITTED',resubmissionOperationId:input.operationId,fieldResubmittedAt:fieldCompletedAt,resubmittedAt:acceptedAt}});await tx.workOrderActivity.create({data:{workOrderId,type:'COMPLETION_CORRECTION_RESUBMITTED',actorId:userId,newStatus:WorkOrderStatus.COMPLETED,note:`Corrected completion resubmitted under authorization ${correctionId}; fresh management acknowledgement required.`}});return updated;
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
 }
}
