import { ConflictException, ForbiddenException } from '@nestjs/common';
import { describe, expect, it, jest } from '@jest/globals';
import { UserRole } from '@prisma/client';
import { WorkOrderCompletionCorrectionService } from './work-order-completion-correction.service';

const input={operationId:'11111111-1111-4111-8111-111111111111',reason:'Bathroom outcome was selected incorrectly.',sectionIds:['22222222-2222-4222-8222-222222222222']};
function authorizationHarness(role:UserRole=UserRole.ADMIN){
 const correction={id:'correction',operationId:input.operationId,requestHash:'hash',workOrderId:'work',status:'AUTHORIZED'};
 const tx:any={workOrderCompletionCorrection:{findUnique:jest.fn(async()=>null),create:jest.fn(async({data}:any)=>({...correction,...data}))},workOrder:{findUnique:jest.fn(async()=>({status:'COMPLETED',startedScopeRevisionId:'scope',completionOperationId:'33333333-3333-4333-8333-333333333333',completedByTechnicianId:'tech',fieldCompletedAt:new Date('2026-08-19T10:00:00Z'),completionAcceptedAt:new Date('2026-08-19T10:01:00Z'),completionAcknowledgedAt:new Date('2026-08-19T11:00:00Z'),completionAcknowledgedById:'manager',completionCorrespondenceEligibleAt:new Date('2026-08-19T11:00:00Z'),completionCorrections:[]}))},workOrderExecutionSection:{findMany:jest.fn(async()=>[{id:input.sectionIds[0],currentOutcomeEvent:{technicianId:'tech'}}])},workOrderTechnician:{findUnique:jest.fn(async()=>({workOrderId:'work',technicianId:'tech'}))},workOrderActivity:{create:jest.fn()}};
 const prisma:any={$transaction:jest.fn(async(cb:any)=>cb(tx))};return{service:new WorkOrderCompletionCorrectionService(prisma),tx,actor:{id:'actor',role}};
}
describe('completion correction authorization',()=>{
 it.each([UserRole.ADMIN,UserRole.SUPERVISOR])('allows %s and snapshots prior completion acknowledgement append-only',async role=>{const{service,tx,actor}=authorizationHarness(role);await service.authorize('work',input,actor);expect(tx.workOrderCompletionCorrection.create).toHaveBeenCalledWith({data:expect.objectContaining({authorizedById:'actor',technicianId:'tech',reason:input.reason,originalCompletionOperationId:'33333333-3333-4333-8333-333333333333',originalAcknowledgedById:'manager'})});expect(tx.workOrder.update).toBeUndefined();});
 it('denies Technician self-authorization',async()=>{const{service,actor}=authorizationHarness(UserRole.TECHNICIAN);await expect(service.authorize('work',input,actor)).rejects.toBeInstanceOf(ForbiddenException);});
 it('requires the submitting Technician to remain assigned',async()=>{const{service,tx,actor}=authorizationHarness();tx.workOrderTechnician.findUnique.mockResolvedValue(null);await expect(service.authorize('work',input,actor)).rejects.toBeInstanceOf(ConflictException);});
 it('is idempotent only for the same authorization payload',async()=>{const{service,tx,actor}=authorizationHarness();const first=await service.authorize('work',input,actor);tx.workOrderCompletionCorrection.findUnique.mockResolvedValue({...first,requestHash:(tx.workOrderCompletionCorrection.create.mock.calls[0][0].data.requestHash)});await expect(service.authorize('work',input,actor)).resolves.toEqual(expect.objectContaining({id:'correction'}));await expect(service.authorize('work',{...input,reason:'Different'},actor)).rejects.toBeInstanceOf(ConflictException);});
});

describe('corrected completion resubmission',()=>{
 it('requires assignment, keeps COMPLETED lifecycle and requires a fresh acknowledgement',async()=>{const correction:any={id:'correction',workOrderId:'work',technicianId:'tech',status:'IN_PROGRESS',workOrder:{status:'COMPLETED',startedScopeRevisionId:'scope',assignedTechnicians:[{technicianId:'tech'}]}};const tx:any={workOrderCompletionCorrection:{findUnique:jest.fn(async()=>null),findFirst:jest.fn(async()=>correction),update:jest.fn(async({data}:any)=>({...correction,...data}))},workOrderExecutionSection:{findMany:jest.fn(async()=>[{title:'Bathroom',currentOutcome:'COMPLETED',currentOutcomeEvent:{reason:null,note:null},evidence:[{id:'evidence-preserved'}]}])},workOrder:{update:jest.fn()},workOrderActivity:{create:jest.fn()}};const prisma:any={employeeRecord:{findFirst:jest.fn(async()=>({technicianId:'tech'}))},$transaction:jest.fn(async(cb:any)=>cb(tx))};const service=new WorkOrderCompletionCorrectionService(prisma);await service.resubmit('user','work','correction',{operationId:'44444444-4444-4444-8444-444444444444',fieldCompletedAt:new Date().toISOString()});expect(tx.workOrder.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({completionAcknowledgedAt:null,completionAcknowledgedById:null,completionCorrespondenceEligibleAt:null})}));expect(tx.workOrderCompletionCorrection.update).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({status:'RESUBMITTED'})}));expect(tx.workOrderExecutionSection.findMany).toHaveBeenCalledWith(expect.objectContaining({where:{scopeRevisionId:'scope'}}));});
});
