import { describe, expect, it } from "@jest/globals";
import * as fs from 'node:fs';import * as path from 'node:path';
const root=path.resolve(__dirname,'../..');const read=(p:string)=>fs.readFileSync(path.join(root,p),'utf8');
describe('Technician completion correction contract',()=>{
 const schema=read('prisma/schema.prisma'),service=read('src/work-orders/work-order-completion-correction.service.ts'),controller=read('src/work-orders/work-orders.controller.ts'),technician=read('src/technician-jobs/technician-jobs.controller.ts');
 it('restricts authorization to ADMIN and SUPERVISOR, never Technician self-authorization',()=>{expect(controller).toContain("@Roles(UserRole.ADMIN, UserRole.SUPERVISOR)\n  authorizeCompletionCorrection");expect(controller).not.toMatch(/authorizeCompletionCorrection[\s\S]{0,100}TECHNICIAN/)});
 it('persists an append-only aggregate and corrected outcome linkage',()=>{expect(schema).toContain('model WorkOrderCompletionCorrection');expect(schema).toContain('correctionId String?');expect(service).toContain('executionSectionOutcomeEvent.create');expect(service).not.toMatch(/executionSectionOutcomeEvent\.(update|delete)/)});
 it('enforces original Technician identity, current assignment and exact frozen section scope',()=>{expect(service).toContain('correction.technicianId!==technicianId');expect(service).toContain('assignedTechnicians:{some:{technicianId}}');expect(service).toContain('correction.affectedSectionIds.includes(sectionId)');expect(service).toContain('startedScopeRevisionId:input.scopeRevisionId')});
 it('retains COMPLETED lifecycle and frozen scope while excluding Finance and correspondence sends',()=>{expect(service).toContain("status:'COMPLETED'");expect(service).not.toMatch(/status:\s*'(ON_SITE|ASSIGNED|NEW)'/);expect(service).not.toMatch(/finance|pricing|message|email|notification/i)});
 it('keeps acknowledgement current at authorization, snapshots history, then clears only on first actual outcome',()=>{const authorize=service.slice(service.indexOf('async authorize'),service.indexOf('private async technician'));expect(authorize).not.toContain('completionAcknowledgedAt:null');expect(service).toContain('priorAcknowledgedAt:job.completionAcknowledgedAt');expect(service).toContain('completionAcknowledgedAt:null');expect(service).toContain('completionCorrespondenceEligibleAt:null')});
 it('provides stable authorization, outcome and resubmission identities with conflicting replay rejection',()=>{expect(schema).toContain('authorizationOperationId String @unique');expect(schema).toContain('operationId String @unique');expect(schema).toContain('resubmissionOperationId String? @unique');expect(service.match(/already used for another/g)?.length).toBeGreaterThanOrEqual(3)});
 it('extends focused management and Technician APIs',()=>{expect(controller).toContain("@Get(':id/completion-corrections')");expect(technician).toContain('correctedOutcome');expect(technician).toContain('correctedResubmit')});
});
