import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash } from 'crypto';
import { Prisma, TechnicianStatus, WorkOrderIncidentCategory, WorkOrderIncidentResolution, WorkOrderIncidentReviewAction } from '@prisma/client';
import { PrismaService } from '../prisma.service';

const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export type ReportIncidentInput={operationId:string;category:WorkOrderIncidentCategory;fieldReportedAt:string;sectionId?:string;note:string;evidence?:Array<{localEvidenceId:string;capturedAt:string;syncState?:'CAPTURED_LOCAL'|'QUEUED'|'RETRY_PENDING'}>};
export type ReviewIncidentInput={operationId:string;action:WorkOrderIncidentReviewAction;resolution?:WorkOrderIncidentResolution;note?:string};
const normalizedHash=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');

@Injectable()
export class WorkOrderIncidentService {
 constructor(private readonly prisma:PrismaService){}
 private async technicianFor(userId:string){const record=await this.prisma.employeeRecord.findFirst({where:{userId,status:'ACTIVE',technician:{status:TechnicianStatus.ACTIVE}},select:{technicianId:true}});if(!record?.technicianId)throw new ForbiddenException('Technician access is not available for this account.');return record.technicianId;}
 async report(userId:string,workOrderId:string,input:ReportIncidentInput){
  const technicianId=await this.technicianFor(userId); if(!UUID.test(input.operationId))throw new BadRequestException('A valid operation ID is required.');
  const fieldReportedAt=new Date(input.fieldReportedAt);const note=input.note?.trim();if(!Number.isFinite(fieldReportedAt.getTime())||fieldReportedAt.getTime()>Date.now()+300000)throw new BadRequestException('A valid field time is required.');if(!note||note.length>1000)throw new BadRequestException('Add a concise factual note (maximum 1000 characters).');
  const normalized={workOrderId,technicianId,category:input.category,fieldReportedAt:fieldReportedAt.toISOString(),sectionId:input.sectionId??null,note,evidence:(input.evidence??[]).map(e=>({localEvidenceId:e.localEvidenceId,capturedAt:new Date(e.capturedAt).toISOString(),syncState:e.syncState??'CAPTURED_LOCAL'}))};const requestHash=normalizedHash(normalized);
  return this.prisma.$transaction(async tx=>{const replay=await tx.workOrderIncident.findUnique({where:{operationId:input.operationId},include:{evidence:true,reviews:true}});if(replay){if(replay.requestHash!==requestHash)throw new ConflictException('This operation ID was already used for another incident.');return replay;}
   const job=await tx.workOrder.findFirst({where:{id:workOrderId,assignedTechnicians:{some:{technicianId}}},select:{jobLeaderId:true,startedScopeRevisionId:true}});if(!job)throw new NotFoundException('Assigned job was not found.');
   if(input.sectionId){const section=await tx.workOrderExecutionSection.findFirst({where:{id:input.sectionId,scopeRevision:{workOrderId},...(job.startedScopeRevisionId?{scopeRevisionId:job.startedScopeRevisionId}:{})},select:{id:true}});if(!section)throw new BadRequestException('The incident section is not part of the active job scope.');}
   const incident=await tx.workOrderIncident.create({data:{operationId:input.operationId,requestHash,workOrderId,technicianId,jobLeaderId:job.jobLeaderId,sectionId:input.sectionId,category:input.category,note,fieldReportedAt}});
   for(const evidence of normalized.evidence){if(!input.sectionId||!job.startedScopeRevisionId)throw new BadRequestException('Incident evidence requires an affected section in the started execution scope.');const existing=await tx.executionSectionEvidence.findUnique({where:{localEvidenceId:evidence.localEvidenceId}});if(existing&&(existing.workOrderId!==workOrderId||existing.sectionId!==input.sectionId||existing.technicianId!==technicianId||existing.purpose!=='INCIDENT_EVIDENCE'))throw new ConflictException('Evidence identity belongs to different execution context.');await tx.executionSectionEvidence.upsert({where:{localEvidenceId:evidence.localEvidenceId},create:{localEvidenceId:evidence.localEvidenceId,workOrderId,scopeRevisionId:job.startedScopeRevisionId,sectionId:input.sectionId,technicianId,purpose:'INCIDENT_EVIDENCE',capturedAt:new Date(evidence.capturedAt),syncState:evidence.syncState,incidentId:incident.id},update:{incidentId:incident.id}});}
   return tx.workOrderIncident.findUniqueOrThrow({where:{id:incident.id},include:{evidence:true,reviews:true}});
  },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
 }
 async list(workOrderId:string){return this.prisma.workOrderIncident.findMany({where:{workOrderId},orderBy:{createdAt:'desc'},include:{technician:{select:{id:true,firstName:true,lastName:true}},section:{select:{id:true,title:true}},evidence:{select:{id:true,localEvidenceId:true,storagePath:true,syncState:true,capturedAt:true,serverAcknowledgedAt:true}},reviews:{orderBy:{createdAt:'asc'},include:{actor:{select:{id:true,firstName:true,lastName:true}}}}}});}
 async review(workOrderId:string,incidentId:string,input:ReviewIncidentInput,actorId:string){if(!UUID.test(input.operationId))throw new BadRequestException('A valid operation ID is required.');if(input.action==='RESOLVE'&&!input.resolution)throw new BadRequestException('Choose a controlled operational resolution.');if(input.action!=='RESOLVE'&&input.resolution)throw new BadRequestException('Resolution applies only when resolving an incident.');const normalized={incidentId,action:input.action,resolution:input.resolution??null,note:input.note?.trim()||null};const requestHash=normalizedHash(normalized);return this.prisma.$transaction(async tx=>{const replay=await tx.workOrderIncidentReview.findUnique({where:{operationId:input.operationId}});if(replay){if(replay.requestHash!==requestHash)throw new ConflictException('This operation ID was already used for another review.');return replay;}const incident=await tx.workOrderIncident.findFirst({where:{id:incidentId,workOrderId}});if(!incident)throw new NotFoundException('Incident was not found.');if(input.action==='ACKNOWLEDGE'&&incident.status==='RESOLVED')throw new ConflictException('A resolved incident must be explicitly reopened first.');if(input.action==='REOPEN'&&incident.status!=='RESOLVED')throw new ConflictException('Only a resolved incident can be reopened.');const review=await tx.workOrderIncidentReview.create({data:{operationId:input.operationId,requestHash,incidentId,actorId,action:input.action,resolution:input.resolution,note:normalized.note}});await tx.workOrderIncident.update({where:{id:incidentId},data:input.action==='RESOLVE'?{status:'RESOLVED',resolvedAt:new Date()}:input.action==='REOPEN'?{status:'OPEN',resolvedAt:null}:{status:'ACKNOWLEDGED'}});return review;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
}
