'use client';

import { FormEvent, useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useRouter, useSearchParams } from 'next/navigation';
import { api, BusinessListOption, CustomerSelectorOption, Property, PropertyInput } from '../../lib/api';
import { displayCustomerName } from '../../lib/customer-display';

type Form = Omit<PropertyInput, 'isEstateOrComplex' | 'requiresGateSecurityAccess' | 'hasPets' | 'hasCameras'> & { isEstateOrComplex: string; requiresGateSecurityAccess: string; hasPets: string; hasCameras: string };
const emptyForm: Form = { customerId: '', propertyTypeOptionId: '', name: '', addressLine1: '', addressLine2: '', city: '', postalCode: '', country: 'South Africa', accessNotes: '', bedrooms: null, bathrooms: null, livingAreas: null, storeys: null, floorSize: null, outdoorArea: null, estateClassification: null, unitFloor: null, isEstateOrComplex: '', requiresGateSecurityAccess: '', parkingNotes: '', hasPets: '', petNotes: '', hasCameras: '', offLimitsNotes: '', fragileItemNotes: '', productRestrictionNotes: '', allergyNotes: '' };
const counts = [{ value: 'ONE', label: '1' }, { value: 'TWO', label: '2' }, { value: 'THREE', label: '3' }, { value: 'FOUR', label: '4' }, { value: 'FIVE_PLUS', label: '5+' }, { value: 'OTHER', label: 'Other' }];
const preciseFloorSizes = [{value:'UNDER_40',label:'Under 40 m²'},{value:'FROM_40_TO_59',label:'40–59 m²'},{value:'FROM_60_TO_79',label:'60–79 m²'},{value:'FROM_80_TO_99',label:'80–99 m²'},{value:'FROM_100_TO_129',label:'100–129 m²'},{value:'FROM_130_TO_169',label:'130–169 m²'},{value:'FROM_170_TO_219',label:'170–219 m²'},{value:'FROM_220_TO_299',label:'220–299 m²'},{value:'FROM_300_UP',label:'300+ m²'},{value:'UNKNOWN',label:'Not sure'}];
const legacyFloorSizeLabels: Record<string, string> = { UNDER_80: 'Under 80 m² (legacy)', FROM_80_TO_150: '80–150 m² (legacy)', FROM_151_TO_250: '151–250 m² (legacy)', OVER_250: 'Over 250 m² (legacy)' };
const floorSizeOptions = (current?: string | null) => current && legacyFloorSizeLabels[current] ? [...preciseFloorSizes, { value: current, label: legacyFloorSizeLabels[current] }] : preciseFloorSizes;
const booleanValue = (value: string) => value === '' ? null : value === 'true';
const booleanFormValue = (value?: boolean | null) => value == null ? '' : String(value);

export function PropertiesManager({ initialItems, initialCustomers, initialPropertyTypes }: { initialItems: Property[]; initialCustomers: CustomerSelectorOption[]; initialPropertyTypes: BusinessListOption[] }) {
  const router = useRouter(), searchParams = useSearchParams();
  const preselectedCustomerId = searchParams.get('mode') === 'create' ? searchParams.get('customerId') : null;
  const [items, setItems] = useState<Property[]>(initialItems), [customers, setCustomers] = useState<CustomerSelectorOption[]>(initialCustomers), [propertyTypes] = useState<BusinessListOption[]>(initialPropertyTypes);
  const [customerSearch, setCustomerSearch] = useState(''), [form, setForm] = useState<Form>(emptyForm), [editingId, setEditingId] = useState<string | null>(null), [error, setError] = useState('');
  const initialCustomerLoad = useRef(true);
  async function load() { try { setItems((await api.properties('?page=1&pageSize=100')).items); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load properties.'); } }
  useEffect(() => { const valid = preselectedCustomerId && initialCustomers.some((customer) => customer.id === preselectedCustomerId); setForm((current) => current.customerId ? current : { ...current, customerId: valid ? preselectedCustomerId : (preselectedCustomerId ? '' : (initialCustomers[0]?.id ?? '')) }); if (preselectedCustomerId && !valid) setError('Validation failed. The selected customer is unavailable.'); }, [initialCustomers, preselectedCustomerId]);
  useEffect(() => { if (initialCustomerLoad.current) { initialCustomerLoad.current = false; return; } const timeout = setTimeout(() => void api.customerSelectorOptions(customerSearch).then(setCustomers).catch((err) => setError(err instanceof Error ? err.message : 'Unable to search customers.')), 200); return () => clearTimeout(timeout); }, [customerSearch]);
  async function submit(event: FormEvent) { event.preventDefault(); try { const input = { ...form, isEstateOrComplex: booleanValue(form.isEstateOrComplex), requiresGateSecurityAccess: booleanValue(form.requiresGateSecurityAccess), hasPets: booleanValue(form.hasPets), hasCameras: booleanValue(form.hasCameras) } as PropertyInput; if (editingId) await api.updateProperty(editingId, input); else { const property = await api.createProperty(input); router.push(`/work-orders/new?customerId=${encodeURIComponent(property.customerId)}&propertyId=${encodeURIComponent(property.id)}`); return; } setEditingId(null); setForm({ ...emptyForm, customerId: customers[0]?.id ?? '' }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save property.'); } }
  function edit(p: Property) { setEditingId(p.id); setForm({ customerId: p.customerId, propertyTypeOptionId: p.propertyTypeOptionId ?? '', name: p.name, addressLine1: p.addressLine1, addressLine2: p.addressLine2 ?? '', city: p.city, postalCode: p.postalCode ?? '', country: p.country, accessNotes: p.accessNotes ?? '', bedrooms: p.bedrooms ?? null, bathrooms: p.bathrooms ?? null, livingAreas: p.livingAreas ?? null, storeys: p.storeys ?? null, floorSize: p.floorSize ?? null, outdoorArea: p.outdoorArea ?? null, estateClassification: p.estateClassification ?? null, unitFloor: p.unitFloor ?? null, isEstateOrComplex: booleanFormValue(p.isEstateOrComplex), requiresGateSecurityAccess: booleanFormValue(p.requiresGateSecurityAccess), parkingNotes: p.parkingNotes ?? '', hasPets: booleanFormValue(p.hasPets), petNotes: p.petNotes ?? '', hasCameras: booleanFormValue(p.hasCameras), offLimitsNotes: p.offLimitsNotes ?? '', fragileItemNotes: p.fragileItemNotes ?? '', productRestrictionNotes: p.productRestrictionNotes ?? '', allergyNotes: p.allergyNotes ?? '' }); }
  async function remove(id: string) { if (!window.confirm('Delete this property?')) return; try { await api.deleteProperty(id); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to delete property.'); } }
  const boolSelect = (field: 'isEstateOrComplex' | 'requiresGateSecurityAccess' | 'hasPets' | 'hasCameras', label: string) => <label>{label}<select value={form[field]} onChange={(e) => setForm({ ...form, [field]: e.target.value })}><option value="">Not recorded</option><option value="true">Yes</option><option value="false">No</option></select></label>;
  const enumSelect = (field: 'bedrooms' | 'bathrooms' | 'livingAreas' | 'storeys' | 'floorSize' | 'outdoorArea' | 'estateClassification' | 'unitFloor', label: string, options: { value: string; label: string }[]) => <label>{label}<select value={form[field] ?? ''} onChange={(e) => setForm({ ...form, [field]: e.target.value || null })}><option value="">Not recorded</option>{options.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></label>;
  return <><header className="pageHeader"><div><p className="eyebrow">Locations</p><h2>Properties</h2><p>Manage each home’s reusable operational profile.</p></div></header>{error ? <p className="errorBanner">{error}</p> : null}<div className="resourceGrid propertyGrid"><form className="panel resourceForm propertyForm" onSubmit={submit}><div className="panelHeader"><h3>{editingId ? 'Edit property' : 'New property'}</h3></div>
    <fieldset className="propertyFormSection"><legend>1. Identity</legend><label>Find customer<input type="search" placeholder="Search by customer or contact name" value={customerSearch} onChange={(e) => setCustomerSearch(e.target.value)} /></label><label>Customer<select required value={form.customerId} onChange={(e) => setForm({ ...form, customerId: e.target.value })}><option value="">Select a customer</option>{customers.map((c) => <option key={c.id} value={c.id}>{displayCustomerName(c)}</option>)}</select></label><label>Property name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label></fieldset>
    <fieldset className="propertyFormSection"><legend>2. Address</legend><label>Address<input required value={form.addressLine1} onChange={(e) => setForm({ ...form, addressLine1: e.target.value })} /></label><label>Address line 2<input value={form.addressLine2 ?? ''} onChange={(e) => setForm({ ...form, addressLine2: e.target.value })} /></label><div className="propertyFieldGrid"><label>City<input required value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></label><label>Postal code<input value={form.postalCode ?? ''} onChange={(e) => setForm({ ...form, postalCode: e.target.value })} /></label></div><label>Country<input value={form.country ?? ''} onChange={(e) => setForm({ ...form, country: e.target.value })} /></label></fieldset>
    <details className="propertyFormSection" open><summary>3. Home profile</summary><div className="propertyFieldGrid"><label>Property type<select value={form.propertyTypeOptionId ?? ''} onChange={(e) => { const option = propertyTypes.find((item) => item.id === e.target.value); const supportsFloor = option?.label === 'Apartment' || option?.label === 'Townhouse'; setForm({ ...form, propertyTypeOptionId: e.target.value, bedrooms: option?.label === 'Apartment' ? form.bedrooms : (form.bedrooms === 'STUDIO' ? null : form.bedrooms), unitFloor: supportsFloor ? form.unitFloor : null }); }}><option value="">Select property type</option>{propertyTypes.map((o) => <option key={o.id} value={o.id}>{o.label}</option>)}</select><small>Manage values in <Link href="/admin/settings/business-lists">Business Lists</Link>.</small></label>{enumSelect('floorSize', 'Floor size', floorSizeOptions(form.floorSize))}{enumSelect('bedrooms', 'Bedrooms', [...(propertyTypes.find((o) => o.id === form.propertyTypeOptionId)?.label === 'Apartment' ? [{ value: 'STUDIO', label: 'Studio' }] : []), ...counts])}{enumSelect('bathrooms', 'Bathrooms', counts.filter((o) => o.value !== 'OTHER'))}{enumSelect('livingAreas', 'Living areas', counts.slice(0, 3).concat({ value: 'FOUR_PLUS', label: '4+' }))}{enumSelect('storeys', 'Storeys', [{value:'ONE',label:'1 storey'},{value:'TWO',label:'2 storeys'},{value:'THREE',label:'3 storeys'},{value:'FOUR_PLUS',label:'4+ storeys'},{value:'UNKNOWN',label:'Not sure'}, ...(form.storeys === 'THREE_PLUS' ? [{value:'THREE_PLUS',label:'3+ (legacy)'}] : [])])}{['Apartment','Townhouse'].includes(propertyTypes.find((o) => o.id === form.propertyTypeOptionId)?.label ?? '') ? enumSelect('unitFloor', 'Unit floor', propertyTypes.find((o) => o.id === form.propertyTypeOptionId)?.label === 'Apartment' ? [{value:'GROUND',label:'Ground floor'},{value:'FIRST',label:'1st floor'},{value:'SECOND',label:'2nd floor'},{value:'THIRD',label:'3rd floor'},{value:'FOURTH',label:'4th floor'},{value:'FIFTH_TO_NINTH',label:'5th–9th floor'},{value:'TENTH_PLUS',label:'10th floor or above'},{value:'UNKNOWN',label:'Not sure'}] : [{value:'GROUND',label:'Ground-level unit'},{value:'FIRST',label:'1st floor'},{value:'SECOND',label:'2nd floor'},{value:'THIRD_PLUS',label:'3rd floor or above'},{value:'UNKNOWN',label:'Not sure'}]) : null}{enumSelect('outdoorArea', 'Outdoor area', [{value:'NONE',label:'None'},{value:'BALCONY',label:'Balcony'},{value:'PATIO',label:'Patio'},{value:'BOTH',label:'Both'}])}</div></details>
    <details className="propertyFormSection"><summary>4. Access & logistics</summary><div className="propertyFieldGrid">{enumSelect('estateClassification', 'Estate / complex classification', [{value:'NONE',label:'No'},{value:'ESTATE',label:'Yes — estate'},{value:'COMPLEX',label:'Yes — complex'},{value:'GATED_COMMUNITY',label:'Yes — gated community'}])}{form.isEstateOrComplex !== '' && !form.estateClassification ? <p className="helpText">Legacy estate/complex answer: {form.isEstateOrComplex === 'true' ? 'Yes — classification unresolved' : 'No'}</p> : null}{boolSelect('requiresGateSecurityAccess', 'Gate/security access required')}</div><label>Access notes<textarea rows={3} value={form.accessNotes ?? ''} onChange={(e) => setForm({ ...form, accessNotes: e.target.value })} /></label><label>Parking notes<textarea rows={2} value={form.parkingNotes ?? ''} onChange={(e) => setForm({ ...form, parkingNotes: e.target.value })} /></label></details>
    <details className="propertyFormSection"><summary>5. Household & care</summary><div className="propertyFieldGrid">{boolSelect('hasPets', 'Pets')}{boolSelect('hasCameras', 'Security cameras')}</div><label>Pet notes<textarea rows={2} value={form.petNotes ?? ''} onChange={(e) => setForm({ ...form, petNotes: e.target.value })} /></label><label>Off-limits areas<textarea rows={2} value={form.offLimitsNotes ?? ''} onChange={(e) => setForm({ ...form, offLimitsNotes: e.target.value })} /></label><label>Fragile / special-care notes<textarea rows={2} value={form.fragileItemNotes ?? ''} onChange={(e) => setForm({ ...form, fragileItemNotes: e.target.value })} /></label><label>Product restrictions<textarea rows={2} value={form.productRestrictionNotes ?? ''} onChange={(e) => setForm({ ...form, productRestrictionNotes: e.target.value })} /></label><label>Operational allergy notes<textarea rows={2} value={form.allergyNotes ?? ''} onChange={(e) => setForm({ ...form, allergyNotes: e.target.value })} /><small>Record only restrictions technicians need to work safely; do not record diagnoses.</small></label></details>
    <div className="formActions"><button className="primaryButton">Save property</button>{editingId ? <button type="button" onClick={() => { setEditingId(null); setForm({ ...emptyForm, customerId: customers[0]?.id ?? '' }); }}>Cancel</button> : null}</div></form>
    <section className="panel"><div className="panelHeader"><h3>Property list</h3></div><div className="dataList">{items.map((p) => <article className="dataRow" key={p.id}><div><strong>{p.name}</strong>{p.propertyTypeOption ? <span className="statusPill">{p.propertyTypeOption.label}</span> : null}<p>{p.customer ? displayCustomerName(p.customer) : 'Customer'} · {p.addressLine1}, {p.city}</p></div><div className="rowActions"><button onClick={() => edit(p)}>Edit</button><button className="dangerButton" onClick={() => void remove(p.id)}>Delete</button></div></article>)}{!items.length ? <div className="emptyState"><strong>No properties found</strong><p>Add a customer first, then create a property.</p></div> : null}</div></section></div></>;
}
