'use client';
import { useEffect,useState } from 'react';
import { AccessRecoverySummary,api,TemporaryAccessCredential } from '../../../lib/api';

export function AccessRecoveryPanel({workOrderId}:{workOrderId:string}){
 const [summary,setSummary]=useState<AccessRecoverySummary|null>(null),[conversationId,setConversationId]=useState(''),[type,setType]=useState<TemporaryAccessCredential['type']>('CODE'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const value=await api.accessRecovery(workOrderId);setSummary(value);setConversationId(current=>current||value.availableChannels[0]?.id||'');}
 useEffect(()=>{void load().catch(()=>setMessage('Unable to load access recovery.'));},[workOrderId]);
 async function send(){setBusy(true);setMessage('');try{await api.initiateAccessRecovery(workOrderId,{requestId:crypto.randomUUID(),conversationId});await load();setMessage('Access recovery request accepted by the selected channel.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to request access information.');}finally{setBusy(false);}}
 async function register(id:string){setBusy(true);try{await api.registerAccessRecoveryCandidate(workOrderId,id,type);await load();setMessage('Protected evidence registered for Admin review. Review it below before it can become usable.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to register protected evidence.');}finally{setBusy(false);}}
 return <section className="panel resourceForm"><div className="panelHeader"><h3>Customer access recovery</h3><span className="statusPill">Admin initiated</span></div><p>This action asks for visit access information through an existing customer conversation. It never sends automatically or changes the Work Order lifecycle.</p>
  {!summary?<p>Loading recovery status…</p>:<><p><strong>{summary.eligible?'Recovery is available':'Recovery is not currently available'}</strong> · Access is {summary.accessReadiness.replaceAll('_',' ').toLowerCase()}.</p>{summary.availableChannels.length?<><label>Messaging channel<select value={conversationId} onChange={e=>setConversationId(e.target.value)}>{summary.availableChannels.map(item=><option key={item.id} value={item.id}>{item.channel==='WHATSAPP'?'WhatsApp':'Facebook Messenger'}</option>)}</select></label><button className="primaryButton" type="button" disabled={busy||!summary.eligible||!conversationId} onClick={()=>void send()}>Request access information</button></>:<p>No configured WhatsApp or Messenger customer conversation is available.</p>}
  <div className="dataList">{summary.attempts.map(item=><article className="dataRow" key={item.id}><div><strong>{item.channel==='WHATSAPP'?'WhatsApp':'Facebook Messenger'} · {item.status.replaceAll('_',' ')}</strong><p>{item.sentAt?`Sent ${new Date(item.sentAt).toLocaleString('en-ZA')}`:'Not delivered'}{item.responseHasAttachment?' · Private attachment received':''}</p></div>{item.responseRequiresReview?<div><label>Evidence type<select value={type} onChange={e=>setType(e.target.value as TemporaryAccessCredential['type'])}><option value="CODE">Code or text</option><option value="QR_IMAGE">QR image</option><option value="QR_DOCUMENT">QR document</option><option value="OTHER">Other</option></select></label><button type="button" disabled={busy} onClick={()=>void register(item.id)}>Register for protected review</button></div>:null}</article>)}</div></>}{message?<p role="status">{message}</p>:null}</section>;
}
