'use client';
import { useCallback,useEffect,useState } from 'react';
import { api,CompletionCorrection,WorkOrder } from '../../../lib/api';
export function CompletionCorrectionPanel({workOrderId}:{workOrderId:string}){
 const [job,setJob]=useState<WorkOrder|null>(null),[history,setHistory]=useState<CompletionCorrection[]>([]),[selected,setSelected]=useState<string[]>([]),[reason,setReason]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 const load=useCallback(async()=>{try{const [workOrder,corrections]=await Promise.all([api.workOrder(workOrderId),api.completionCorrections(workOrderId)]);setJob(workOrder);setHistory(corrections);}catch(e){setError(e instanceof Error?e.message:'Unable to load completion corrections.');}},[workOrderId]);useEffect(()=>{void load()},[load]);
 const sections=(job as any)?.startedScopeRevision?.sections??[];const active=history.some(x=>x.status!=="RESUBMITTED");
 async function authorize(){if(!reason.trim()||!selected.length)return;setSaving(true);setError('');try{await api.authorizeCompletionCorrection(workOrderId,{operationId:crypto.randomUUID(),reason:reason.trim(),sectionIds:selected});setReason('');setSelected([]);await load();}catch(e){setError(e instanceof Error?e.message:'Unable to authorize correction.');}finally{setSaving(false)}}
 if(!job||job.status!=="COMPLETED")return null;
 return <section className="panel resourceForm"><div className="panelHeader"><h3>Completion corrections</h3><span>{history.length} authorization(s)</span></div>{error?<p className="errorBanner">{error}</p>:null}{history.map(c=><article className="dataRow" key={c.id}><div><strong>{c.status.replace('_',' ')}</strong><p>{c.reason}</p><small>Authorized by {c.authorizedBy.firstName} {c.authorizedBy.lastName} for {c.technician.firstName} {c.technician.lastName} · {new Date(c.createdAt).toLocaleString()}</small><p><strong>Authorized sections:</strong> {sections.filter((s:any)=>c.affectedSectionIds.includes(s.id)).map((s:any)=>s.title).join(' · ')}</p><p><strong>Original completion:</strong> {new Date(c.originalFieldCompletedAt).toLocaleString()}<br/><strong>First corrected outcome:</strong> {c.firstCorrectedAt?new Date(c.firstCorrectedAt).toLocaleString():'Not yet recorded'}<br/><strong>Corrected resubmission:</strong> {c.resubmittedAt?new Date(c.resubmittedAt).toLocaleString():'Not yet resubmitted'}</p>{c.correctedOutcomes.map(o=><p key={o.id}><strong>{o.section.title} corrected to {o.outcome}</strong> · {new Date(o.fieldRecordedAt).toLocaleString()}{o.reason?` · ${o.reason}`:''}{o.note?` · ${o.note}`:''}</p>)}</div></article>)}{!history.length?<p>No completion correction has been authorized.</p>:null}{!active?<><h4>Authorize a genuine correction</h4><p>The Work Order remains completed. Select only the frozen-scope sections requiring factual correction.</p>{sections.map((s:any)=><label key={s.id}><input type="checkbox" checked={selected.includes(s.id)} onChange={e=>setSelected(e.target.checked?[...selected,s.id]:selected.filter(id=>id!==s.id))}/>{s.title}</label>)}<label>Concise factual reason<textarea minLength={5} maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="primaryButton" disabled={saving||reason.trim().length<5||!selected.length} onClick={()=>void authorize()}>{saving?'Authorizing…':'Authorize correction'}</button></>:<p>An active correction already exists for this Work Order.</p>}</section>
}
