'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { createClient } from '../../../lib/supabase/client';
import { createWorkOrderReplacementVisit, InterruptionNextAction, routeWorkOrderInterruption, workOrderInterruption, workOrderReplacementVisit, InterruptionDetail, ReplacementVisitDetail } from '../../../lib/work-order-interruption-api';

const actions:Array<[InterruptionNextAction,string]>=[
  ['REPLACEMENT_VISIT','Create replacement visit'],
  ['FOLLOW_UP','Customer / operational follow-up'],
  ['PARTIAL_COMPLETION_REVIEW','Review partial completion'],
  ['FINANCIAL_REVIEW','Financial resolution required'],
  ['CLOSE','Close attempted visit'],
];
const reasonLabels:Record<string,string>={NO_ACCESS:'No access after attendance',UTILITIES_UNAVAILABLE:'Required utilities unavailable',SAFETY_CONCERN:'Safety concern',CUSTOMER_REQUESTED:'Customer requested interruption',REQUIRED_RESOURCE_UNAVAILABLE:'Required resource unavailable',OTHER:'Other'};
async function token(){const {data:{session}}=await createClient().auth.getSession();if(!session?.access_token)throw new Error('An authenticated management session is required.');return session.access_token;}

export function InterruptedVisitAdminPanel({workOrderId,canRoute}:{workOrderId:string;canRoute:boolean}){
  const [detail,setDetail]=useState<InterruptionDetail|null>(null),[replacement,setReplacement]=useState<ReplacementVisitDetail|null>(null),[action,setAction]=useState<InterruptionNextAction>('FOLLOW_UP'),[note,setNote]=useState(''),[replacementTime,setReplacementTime]=useState(''),[replacementNote,setReplacementNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const load=useCallback(async()=>{try{const accessToken=await token();const [nextDetail,nextReplacement]=await Promise.all([workOrderInterruption(workOrderId,accessToken),workOrderReplacementVisit(workOrderId,accessToken)]);setDetail(nextDetail);setReplacement(nextReplacement);}catch(error){setMessage(error instanceof Error?error.message:'Unable to load interruption review.');}},[workOrderId]);
  useEffect(()=>{void load();},[load]);
  if(!detail?.interruption)return null;
  async function route(){setBusy(true);setMessage('');try{await routeWorkOrderInterruption(workOrderId,await token(),{operationId:crypto.randomUUID(),nextAction:action,note:note.trim()||undefined});setMessage(action==='CLOSE'?'Interrupted visit closed.':'Next action recorded. The original attempted visit remains preserved.');setNote('');await load();}catch(error){setMessage(error instanceof Error?error.message:'Unable to record the next action.');}finally{setBusy(false);}}
  async function createReplacement(){if(!replacementTime){setMessage('Choose the replacement service date and time.');return;}setBusy(true);setMessage('');try{const scheduledAt=new Date(replacementTime);if(!Number.isFinite(scheduledAt.getTime()))throw new Error('Choose a valid replacement service date and time.');const created=await createWorkOrderReplacementVisit(workOrderId,await token(),{operationId:crypto.randomUUID(),scheduledAt:scheduledAt.toISOString(),note:replacementNote.trim()||undefined});setReplacement(created);setMessage(`Replacement Work Order ${created.replacement?.reference??created.replacementWorkOrderId} created. The original interrupted visit was not changed.`);setReplacementNote('');await load();}catch(error){setMessage(error instanceof Error?error.message:'Unable to create the replacement visit.');}finally{setBusy(false);}}
  const replacementRouted=detail.latestRoute?.nextAction==='REPLACEMENT_VISIT';
  return <article className="executionChecklist"><h2>Interrupted visit review</h2><p><strong>{reasonLabels[detail.interruption.reason]??detail.interruption.reason}</strong><br/>{detail.interruption.note}</p><p>Field time: {new Date(detail.interruption.fieldInterruptedAt).toLocaleString()}</p>{detail.latestRoute?<p><strong>Latest route:</strong> {detail.latestRoute.nextAction.replaceAll('_',' ').toLowerCase()}{detail.latestRoute.note?` · ${detail.latestRoute.note}`:''}</p>:<p className="syncNotice">Management routing required.</p>}{detail.routes.length?<details><summary>Routing history ({detail.routes.length})</summary>{detail.routes.map(item=><p key={item.id}>{new Date(item.createdAt).toLocaleString()} · {item.nextAction.replaceAll('_',' ').toLowerCase()}{item.note?` · ${item.note}`:''}</p>)}</details>:null}{replacement?.replacement?<section><h3>Linked replacement visit</h3><p><Link href={`/work-orders/${replacement.replacement.id}`}>{replacement.replacement.reference??'Replacement Work Order'}</Link> · {replacement.replacement.status.toLowerCase()} · {replacement.replacement.scheduledAt?new Date(replacement.replacement.scheduledAt).toLocaleString():'Not scheduled'}</p><p className="syncNotice">This is a separate Work Order. The interrupted attempt, field evidence and history remain unchanged.</p></section>:null}{canRoute&&detail.status==='INTERRUPTED'&&!replacement?<><label>Next action<select value={action} onChange={e=>setAction(e.target.value as InterruptionNextAction)}>{actions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Management note<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="Optional factual routing note" /></label><button type="button" disabled={busy} onClick={()=>void route()}>{busy?'Saving…':'Record next action'}</button></>:null}{canRoute&&detail.status==='INTERRUPTED'&&replacementRouted&&!replacement?<section><h3>Create replacement visit</h3><p className="syncNotice">A new unassigned Work Order will be created. Customer, property, booked service/add-ons and non-secret visit context carry forward. Technician assignment, evidence, outcomes, temporary access credentials and interruption history do not.</p><label>Replacement service date and time<input type="datetime-local" value={replacementTime} onChange={e=>setReplacementTime(e.target.value)} /></label><label>Replacement note<textarea value={replacementNote} onChange={e=>setReplacementNote(e.target.value)} maxLength={1000} placeholder="Optional operational note" /></label><button type="button" disabled={busy||!replacementTime} onClick={()=>void createReplacement()}>{busy?'Creating…':'Create linked replacement Work Order'}</button></section>:null}{action==='FINANCIAL_REVIEW'?<p className="syncNotice">This flags financial review only. It does not create or change any charge, payment, credit or refund.</p>:null}{message?<p className="syncNotice">{message}</p>:null}</article>;
}
