'use client';

import { useEffect, useState } from 'react';
import { createClient } from '../../../lib/supabase/client';
import { CustomerApprovalMethod, CustomerApprovalStatus, listScopeMismatches, resolveScopeMismatch, ScopeMismatch, ScopeMismatchResolutionCode } from '../../../lib/work-order-scope-mismatch-api';

async function token(){const {data:{session}}=await createClient().auth.getSession();if(!session?.access_token)throw new Error('An authenticated Admin session is required.');return session.access_token}
const resolutionLabels:Record<ScopeMismatchResolutionCode,string>={NO_CHANGE_REQUIRED:'No scope change required',NON_CHARGEABLE_ADJUSTMENT:'Approve non-chargeable adjustment',CHARGEABLE_ADDITIONAL_WORK:'Chargeable additional work',DECLINE_ADDITIONAL_WORK:'Do not perform additional work'};

export function ScopeMismatchAdminPanel({workOrderId}:{workOrderId:string}){
  const [items,setItems]=useState<ScopeMismatch[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function load(){try{setError('');setItems((await listScopeMismatches(workOrderId,await token())).mismatches)}catch(e){setError(e instanceof Error?e.message:'Unable to load scope mismatches.')}}
  useEffect(()=>{void load()},[workOrderId]);
  return <section className="card" style={{marginTop:16}}><h2>Scope mismatch review</h2><p className="muted">Technicians report what differs from the frozen scope. Admin controls any commercial decision; the original field scope is never rewritten.</p>{error?<p className="error">{error}</p>:null}{items.length===0?<p className="muted">No scope mismatches have been reported.</p>:items.map(item=><MismatchCard key={item.id} item={item} disabled={busy} onSave={async input=>{setBusy(true);try{await resolveScopeMismatch(workOrderId,item.id,await token(),{operationId:crypto.randomUUID(),...input});await load()}catch(e){setError(e instanceof Error?e.message:'Unable to save resolution.')}finally{setBusy(false)}}}/>)}</section>
}

function MismatchCard({item,disabled,onSave}:{item:ScopeMismatch;disabled:boolean;onSave:(input:{resolution:ScopeMismatchResolutionCode;customerApprovalStatus?:CustomerApprovalStatus;customerApprovalMethod?:CustomerApprovalMethod;customerApprovedAt?:string;proposedAmountMinor?:number;capacityReviewed?:boolean;note?:string})=>Promise<void>}){
  const [resolution,setResolution]=useState<ScopeMismatchResolutionCode>('NO_CHANGE_REQUIRED');const [approval,setApproval]=useState<CustomerApprovalStatus>('PENDING');const [method,setMethod]=useState<CustomerApprovalMethod>('PHONE');const [amount,setAmount]=useState('');const [capacity,setCapacity]=useState(false);const [note,setNote]=useState('');
  const chargeable=resolution==='CHARGEABLE_ADDITIONAL_WORK';
  return <div className="card" style={{marginTop:12}}><strong>{item.section.title}</strong><p>{item.note||'Technician reported a scope or condition mismatch.'}</p><p className="muted">Reported by {item.technician.firstName} {item.technician.lastName} · {new Date(item.fieldRecordedAt).toLocaleString()}</p>{item.latestResolution?<p><strong>Latest management outcome:</strong> {resolutionLabels[item.latestResolution.resolution]}{item.additionalWorkMayBegin?' · Customer approval recorded':''}</p>:null}<label>Management outcome<select value={resolution} onChange={e=>setResolution(e.target.value as ScopeMismatchResolutionCode)} disabled={disabled}>{Object.entries(resolutionLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{chargeable?<><label>Proposed additional amount (R)<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} disabled={disabled}/></label><label><input type="checkbox" checked={capacity} onChange={e=>setCapacity(e.target.checked)} disabled={disabled}/> Capacity and scheduling impact reviewed</label><label>Customer approval<select value={approval} onChange={e=>setApproval(e.target.value as CustomerApprovalStatus)} disabled={disabled}><option value="PENDING">Pending</option><option value="APPROVED">Approved</option><option value="DECLINED">Declined</option></select></label>{approval==='APPROVED'?<><label>Approval method<select value={method} onChange={e=>setMethod(e.target.value as CustomerApprovalMethod)} disabled={disabled}><option value="PHONE">Phone</option><option value="WHATSAPP">WhatsApp</option><option value="EMAIL">Email</option><option value="IN_PERSON">In person</option><option value="OTHER">Other</option></select></label></>:null}</>:null}<label>Management note<textarea value={note} onChange={e=>setNote(e.target.value)} disabled={disabled}/></label><button type="button" disabled={disabled} onClick={()=>void onSave({resolution,customerApprovalStatus:chargeable?approval:undefined,customerApprovalMethod:chargeable&&approval==='APPROVED'?method:undefined,customerApprovedAt:chargeable&&approval==='APPROVED'?new Date().toISOString():undefined,proposedAmountMinor:chargeable&&amount?Math.round(Number(amount)*100):undefined,capacityReviewed:chargeable?capacity:undefined,note:note||undefined})}>Save management resolution</button>{chargeable&&approval!=='APPROVED'?<p className="muted">Additional chargeable work must not begin until customer approval is recorded.</p>:null}</div>
}
