'use client';
import { useEffect,useState } from 'react';
import { api,TemporaryAccessCredential } from '../../../lib/api';

export function TemporaryAccessCredentialsPanel({workOrderId}:{workOrderId:string}){
 const [items,setItems]=useState<TemporaryAccessCredential[]>([]),[secret,setSecret]=useState(''),[expiresAt,setExpiresAt]=useState(''),[singleUse,setSingleUse]=useState(false),[message,setMessage]=useState(''),[revealed,setRevealed]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false);
 async function load(){setItems(await api.temporaryAccessCredentials(workOrderId));}
 useEffect(()=>{void load().catch(()=>setMessage('Unable to load protected credentials.'));},[workOrderId]);
 async function create(){setBusy(true);setMessage('');try{await api.createTemporaryAccessCredential(workOrderId,{requestId:crypto.randomUUID(),type:'CODE',protectedText:secret,expiresAt:expiresAt?new Date(expiresAt).toISOString():undefined,singleUse});setSecret('');setExpiresAt('');setSingleUse(false);await load();setMessage('Credential stored for review.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to store credential.');}finally{setBusy(false);}}
 async function review(item:TemporaryAccessCredential,decision:'ACCEPT'|'REJECT'){setBusy(true);try{await api.reviewTemporaryAccessCredential(workOrderId,item.id,decision);await load();setMessage(`Credential ${decision==='ACCEPT'?'accepted':'rejected'}.`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to review credential.');}finally{setBusy(false);}}
 async function reveal(item:TemporaryAccessCredential){try{const value=await api.revealTemporaryAccessCredential(workOrderId,item.id);setRevealed(current=>({...current,[item.id]:value.protectedText??(value.attachmentStoragePath?'Private attachment available.':'No protected value.')}));await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to reveal credential.');}}
 return <section className="panel resourceForm"><div className="panelHeader"><h3>Protected temporary access</h3><span className="statusPill">Admin only</span></div><p>Credentials are limited to this visit. Values stay hidden until an explicit, audited reveal and never carry into another Work Order.</p>
  <label>Protected credential text<input type="password" autoComplete="new-password" value={secret} maxLength={2000} onChange={e=>setSecret(e.target.value)} /></label><label>Expires at<input type="datetime-local" value={expiresAt} onChange={e=>setExpiresAt(e.target.value)} /></label><label><input type="checkbox" checked={singleUse} onChange={e=>setSingleUse(e.target.checked)} /> Single use</label><button type="button" className="primaryButton" disabled={busy||!secret.trim()} onClick={()=>void create()}>Store for review</button>{message?<p role="status">{message}</p>:null}
  <div className="dataList">{items.map(item=><article className="dataRow" key={item.id}><div><strong>{item.type.replaceAll('_',' ')} · {item.reviewStatus.replaceAll('_',' ')}</strong><p>{item.expiresAt?`Expires ${new Date(item.expiresAt).toLocaleString('en-ZA')}`:'No expiry recorded'}{item.singleUse?' · Single use':''}</p>{item.attachmentFileName?<p>Protected attachment: {item.attachmentFileName}</p>:null}{revealed[item.id]?<p><strong>Revealed:</strong> {revealed[item.id]}</p>:null}</div><div>{item.reviewStatus==='PENDING_REVIEW'?<><button type="button" disabled={busy} onClick={()=>void review(item,'ACCEPT')}>Accept</button><button type="button" disabled={busy} onClick={()=>void review(item,'REJECT')}>Reject</button></>:null}{item.reviewStatus==='ACCEPTED'?<><button type="button" onClick={()=>void reveal(item)}>Reveal</button><button type="button" onClick={()=>void api.revokeTemporaryAccessCredential(workOrderId,item.id).then(load)}>Revoke</button></>:null}</div></article>)}</div>
 </section>;
}
