'use client';
import Link from 'next/link'; import { useCallback,useEffect,useState } from 'react'; import { ApiError,technicianApi,TechnicianJob } from '../../../lib/api'; import { cachedJob,cacheJobs,pendingStarts,removeCachedJob,removePendingStart,savePendingStart } from './offline-store';
const uuid=()=>crypto.randomUUID();
export function JobBrief({id}:{id:string}) { const [job,setJob]=useState<TechnicianJob|null>(null),[offline,setOffline]=useState(false),[pending,setPending]=useState(0),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const reconcile=useCallback(async()=>{try{for(const operation of await pendingStarts()){try{const updated=await technicianApi.start(operation.workOrderId,operation);await cacheJobs([updated]);await removePendingStart(operation.operationId);}catch{/* authoritative conflict remains queued for explicit future resolution */}}const fresh=await technicianApi.job(id);await cacheJobs([fresh]);setJob(fresh);setOffline(false);}catch(error){if(error instanceof ApiError&&(error.status===403||error.status===404)){await removeCachedJob(id);setJob(null);setMessage('This job is no longer assigned to you.');setOffline(false);}else{setJob(await cachedJob(id)??null);setOffline(true);}}finally{setPending((await pendingStarts()).length);}},[id]);
 useEffect(()=>{void reconcile();const online=()=>void reconcile();window.addEventListener('online',online);return()=>window.removeEventListener('online',online);},[reconcile]);
 async function start(){if(!job?.canStart)return;setBusy(true);const operation={kind:'START_JOB' as const,workOrderId:id,operationId:uuid(),startedAt:new Date().toISOString(),expectedVersion:job.updatedAt,queuedAt:new Date().toISOString()};try{await savePendingStart(operation);setPending(p=>p+1);const local={...job,startedAt:operation.startedAt,canStart:false,status:'ON_SITE' as const};await cacheJobs([local]);setJob(local);setMessage('Job started on this device · Sync pending');if(navigator.onLine)await reconcile();}catch{setMessage('Could not safely save the start. Try again.');}finally{setBusy(false);}}
 if(!job)return <section className="technicianPage"><Link href="/technician">← Today</Link><p>{offline?'This job is not available offline on this device.':'Loading Job Brief…'}</p></section>;
 const address=[job.property.addressLine1,job.property.addressLine2,job.property.city,job.property.province,job.property.postalCode].filter(Boolean).join(', '); const context=[job.property.bedrooms&&`${job.property.bedrooms} bedrooms`,job.property.bathrooms&&`${job.property.bathrooms} bathrooms`,job.property.hasPets&&(job.property.petNotes||'Pets present'),job.property.offLimitsNotes,job.property.fragileItemNotes,job.property.productRestrictionNotes,job.property.allergyNotes].filter(Boolean);
 return <section className="technicianPage jobBrief"><Link href="/technician">← Assigned jobs</Link><div className="technicianHeading"><p className="eyebrow">Job brief</p><h1>{job.service?.name??job.title}</h1><span className={`syncBadge ${offline||pending?'pending':''}`}>{offline?'Offline · Saved on device':pending?`${pending} update waiting to sync`:'Synced'}</span></div>{message?<p className="syncNotice">{message}</p>:null}<article><h2>Job</h2><p><strong>{job.reference??'Work order'}</strong><br/>{job.scheduledAt?new Intl.DateTimeFormat('en-ZA',{dateStyle:'full',timeStyle:'short'}).format(new Date(job.scheduledAt)):'Schedule to be confirmed'}<br/>{address}<br/><span className="statusPill">{job.status.replaceAll('_',' ')}</span></p></article><article><h2>Team</h2>{job.assignedTechnicians.map(({technician,technicianId})=><p key={technicianId}>{technician.firstName} {technician.lastName}{technicianId===job.jobLeaderId?' · Job Leader':''}</p>)}{job.isJobLeader?<strong>You are Job Leader</strong>:null}</article><article><h2>What you’re doing</h2><p><strong>{job.service?.name??job.title}</strong>{job.service?.description?<><br/>{job.service.description}</>:null}{job.description?<><br/>{job.description}</>:null}</p>{job.addOns.map(a=><p key={a.service.name}>{a.service.name} × {a.quantity}</p>)}</article><article><h2>Arrival / access</h2><p>{[job.parkingInstructions,job.property.parkingNotes,job.accessInstructions,job.property.accessNotes,job.keyHandover,job.keyHandoverDetails,job.someonePresent===true?'Customer will be present':job.someonePresent===false?'Customer will not be present':null].filter(Boolean).join(' · ')||'No ordinary arrival instructions recorded.'}</p></article>{context.length?<article><h2>Important context</h2><p>{context.join(' · ')}</p></article>:null}{job.canStart?<button className="technicianStart" disabled={busy} onClick={()=>void start()}>{busy?'Saving…':'Start Job'}</button>:job.waitingForJobLeader?<p className="waitingState">Waiting for Job Leader to start the job</p>:job.startedAt?<p className="waitingState">Started {new Intl.DateTimeFormat('en-ZA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(job.startedAt))}</p>:null}</section>;
}
