'use client';
import Link from 'next/link'; import { useCallback, useEffect, useState } from 'react';
import { technicianApi, TechnicianJob, TechnicianJobList } from '../../../lib/api'; import { cachedJobs, replaceAssignedCache, pendingStarts } from './offline-store'; import { TechnicianServiceWorker } from './service-worker';
const views=['today','upcoming','recent'] as const;
function time(job:TechnicianJob){return job.scheduledAt?new Intl.DateTimeFormat('en-ZA',{hour:'2-digit',minute:'2-digit'}).format(new Date(job.scheduledAt)):'Time to be confirmed';}
export function TechnicianHome({initialView}:{initialView:string}) { const view=views.includes(initialView as any)?initialView as TechnicianJobList['view']:'today'; const [jobs,setJobs]=useState<TechnicianJob[]>([]); const [offline,setOffline]=useState(false); const [pending,setPending]=useState(0); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{const [result,cacheResult]=await Promise.all([technicianApi.jobs(view),technicianApi.jobs('cache')]);setJobs(result.jobs);await replaceAssignedCache(cacheResult.jobs);setOffline(false);}catch{const all=await cachedJobs(); const now=new Date(), start=new Date(now);start.setHours(0,0,0,0);const tomorrow=new Date(start.getTime()+86400000);setJobs(all.filter(j=>{const date=j.scheduledAt?new Date(j.scheduledAt):null;if(!date)return false;if(view==='today')return date>=start&&date<tomorrow;if(view==='upcoming')return date>=tomorrow;return date<start;}));setOffline(true);}finally{setPending((await pendingStarts()).length);setLoading(false);}},[view]);
 useEffect(()=>{void load(); const online=()=>void load(); const visible=()=>{if(document.visibilityState==='visible')void load();};window.addEventListener('online',online);document.addEventListener('visibilitychange',visible);return()=>{window.removeEventListener('online',online);document.removeEventListener('visibilitychange',visible);};},[load]);
 return <><TechnicianServiceWorker/><section className="technicianPage"><div className="technicianHeading"><p className="eyebrow">{view}</p><h1>{view==='today'?'Today':view[0].toUpperCase()+view.slice(1)}</h1><span className={`syncBadge ${offline?'pending':''}`}>{offline?'Offline · Saved on device':pending?`${pending} update${pending===1?'':'s'} waiting to sync`:'Synced'}</span></div>{loading?<p>Loading assigned jobs…</p>:<div className="technicianJobs">{jobs.map(job=><Link className="technicianJobCard" href={`/technician/jobs/${job.id}`} key={job.id}><time>{time(job)}</time><h2>{job.service?.name??job.title}</h2><p>{job.property.name} · {job.property.city}</p>{job.isJobLeader?<strong>You are Job Leader</strong>:null}<span>{job.status.replaceAll('_',' ')}</span></Link>)}{!jobs.length?<div className="emptyState"><strong>No assigned jobs</strong><p>Your assignment-scoped schedule has no jobs in this view.</p></div>:null}</div>}</section></>;
}
