'use client';
import { useEffect, useState } from 'react';
import { api, CustomerCleanupImpact, CustomerSelectorOption } from '../../../../lib/api';
import { displayCustomerName } from '../../../../lib/customer-display';

const warning = 'This permanently deletes the selected customer and customer-owned operational records, including linked properties and work orders. This action cannot be undone.';
export function CustomerDataCleanup() {
  const [customers, setCustomers] = useState<CustomerSelectorOption[]>([]), [selectedId, setSelectedId] = useState(''), [impact, setImpact] = useState<CustomerCleanupImpact | null>(null);
  const [confirming, setConfirming] = useState(false), [confirmation, setConfirmation] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  useEffect(() => { void api.customerSelectorOptions().then(setCustomers).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load customers.')); }, []);
  async function preview(id: string) { setSelectedId(id); setImpact(null); setConfirming(false); setConfirmation(''); setMessage(''); if (!id) return; try { setImpact(await api.customerCleanupImpact(id)); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Unable to preview cleanup.'); } }
  async function remove() { if (!impact || confirmation !== impact.customerName || busy) return; setBusy(true); try { const result = await api.customerCleanup(selectedId, confirmation); setMessage(`Customer file deleted: ${result.propertiesDeleted} properties, ${result.workOrdersDeleted} work orders, and ${result.activitiesDeleted + result.checklistItemsDeleted + result.photosDeleted + result.signOffsDeleted} child records.`); setCustomers(customers.filter((x) => x.id !== selectedId)); setSelectedId(''); setImpact(null); setConfirming(false); setConfirmation(''); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Cleanup failed. No records were deleted.'); } finally { setBusy(false); } }
  return <>
    <header className="pageHeader"><div><p className="eyebrow">Admin Settings · Data Management</p><h2>Customer Data Cleanup</h2><p>Clear complete test customer scenarios without weakening normal Customer deletion protections.</p></div></header>
    {error ? <p className="errorBanner" role="alert">{error}</p> : null}{message ? <p className="successBanner" role="status">{message}</p> : null}
    <section className="panel destructivePanel"><h3>Select customer</h3><label>Customer Contact<select value={selectedId} onChange={(e) => void preview(e.target.value)}><option value="">Select a customer</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{displayCustomerName(customer)}</option>)}</select></label></section>
    {impact ? <section className="panel destructivePanel"><h3>{impact.customerName}</h3><p>Authoritative deletion impact</p><dl className="impactGrid"><div><dt>Customer</dt><dd>{impact.customer}</dd></div><div><dt>Properties</dt><dd>{impact.properties}</dd></div><div><dt>Work Orders</dt><dd>{impact.workOrders}</dd></div><div><dt>Activities</dt><dd>{impact.activities}</dd></div><div><dt>Checklist records</dt><dd>{impact.checklistItems}</dd></div><div><dt>Photo records</dt><dd>{impact.photos}</dd></div><div><dt>Sign-offs</dt><dd>{impact.signOffs}</dd></div><div><dt>Shifts preserved / detached</dt><dd>{impact.shiftsToDetach}</dd></div></dl>{!confirming ? <button type="button" className="dangerButton" onClick={() => setConfirming(true)}>Delete customer file</button> : <div className="irreversibleWarning"><strong>Irreversible action</strong><p>{warning}</p><label>Type <strong>{impact.customerName}</strong> exactly to confirm<input autoComplete="off" aria-describedby="cleanup-confirmation-feedback" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /></label>{confirmation && confirmation !== impact.customerName ? <p id="cleanup-confirmation-feedback" className="confirmationMismatch" role="alert">Name does not match. Type “{impact.customerName}” exactly.</p> : null}<button type="button" className="dangerButton cleanupDeleteButton" disabled={confirmation !== impact.customerName || busy} onClick={() => void remove()}>{busy ? 'Deleting…' : 'Permanently delete customer file'}</button></div>}</section> : null}
  </>;
}
