import { describe, expect, it, jest } from '@jest/globals';
import { ConflictException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { WorkOrderStatus } from '@prisma/client';
import { TechnicianJobsService } from './technician-jobs.service';
const version = new Date('2026-08-17T08:00:00.000Z');
const operation = { operationId: '11111111-1111-4111-8111-111111111111', startedAt: '2026-08-17T08:05:00.000Z', expectedVersion: version.toISOString() };
const job:any = { id:'wo-1',reference:'WO-1',title:'Deep Cleaning',description:'Use eco products',status:WorkOrderStatus.ASSIGNED,scheduledAt:version,preferredTimeWindow:null,updatedAt:version,startedAt:null,startOperationId:null,jobLeaderId:'tech-1',service:{name:'Deep Cleaning',description:null},addOns:[],assignedTechnicians:[{technicianId:'tech-1',technician:{id:'tech-1',firstName:'Ada',lastName:'A'}}],property:{name:'Orange Farm',addressLine1:'1 Main',city:'Johannesburg'},accessInstructions:null,parkingInstructions:null,keyHandover:null,keyHandoverDetails:null,someonePresent:null,ecoFriendlyProducts:true,customerDeclaredExistingDamage:null};
function harness(record:any={technicianId:'tech-1'}) { const tx:any={workOrder:{findFirst:jest.fn(async()=>job),updateMany:jest.fn(async()=>({count:1}))},workOrderActivity:{create:jest.fn(async()=>({}))}}; const prisma:any={employeeRecord:{findFirst:jest.fn(async()=>record)},workOrder:{findMany:jest.fn(async()=>[job]),findFirst:jest.fn(async()=>job)},$transaction:jest.fn(async(cb:any)=>cb(tx))}; return {service:new TechnicianJobsService(prisma),prisma,tx}; }
describe('Technician assignment-scoped jobs',()=>{
 it('returns only the canonical Technician assignment query and a minimized DTO',async()=>{const {service,prisma}=harness();const result=await service.list('admin-tech','today');expect(prisma.workOrder.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({assignedTechnicians:{some:{technicianId:'tech-1'}}})}));expect(result.jobs[0]).not.toHaveProperty('customer');expect(result.jobs[0]).not.toHaveProperty('temporaryAccessCredentials');expect(result.jobs[0]).not.toHaveProperty('sourceQuote');});
 it('rejects ADMIN-only accounts without a linked active Technician',async()=>{const {service}=harness(null);await expect(service.list('admin','today')).rejects.toBeInstanceOf(ForbiddenException);});
 it('fails closed for guessed or removed assignments',async()=>{const {service,prisma}=harness();prisma.workOrder.findFirst.mockResolvedValue(null);await expect(service.brief('user','other-wo')).rejects.toBeInstanceOf(NotFoundException);});
 it('allows an assigned non-leader to view the brief but not start',async()=>{const {service,tx}=harness({technicianId:'tech-2'});const brief=await service.brief('user','wo-1');expect(brief.waitingForJobLeader).toBe(true);await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ForbiddenException);expect(tx.workOrderActivity.create).not.toHaveBeenCalled();});
 it('starts once with actual time, canonical ON_SITE lifecycle and one audit',async()=>{const {service,tx}=harness();await service.start('user','wo-1',operation);expect(tx.workOrder.updateMany).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({startedAt:new Date(operation.startedAt),startedByTechnicianId:'tech-1',startOperationId:operation.operationId,status:WorkOrderStatus.ON_SITE})}));expect(tx.workOrderActivity.create).toHaveBeenCalledTimes(1);expect(tx.workOrderActivity.create).toHaveBeenCalledWith({data:expect.objectContaining({type:'JOB_STARTED',previousStatus:WorkOrderStatus.ASSIGNED,newStatus:WorkOrderStatus.ON_SITE})});expect(job.scheduledAt).toEqual(version);});
 it('reconciles the identical operation without another update or activity',async()=>{const {service,tx}=harness();tx.workOrder.findFirst.mockResolvedValue({...job,startedAt:new Date(operation.startedAt),startOperationId:operation.operationId,status:WorkOrderStatus.ON_SITE});await service.start('user','wo-1',operation);expect(tx.workOrder.updateMany).not.toHaveBeenCalled();expect(tx.workOrderActivity.create).not.toHaveBeenCalled();});
 it('rejects incompatible replay, cancellation and stale cached versions',async()=>{const {service,tx}=harness();tx.workOrder.findFirst.mockResolvedValue({...job,startedAt:new Date(),startOperationId:'22222222-2222-4222-8222-222222222222'});await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ConflictException);tx.workOrder.findFirst.mockResolvedValue({...job,status:WorkOrderStatus.CANCELLED});await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ConflictException);tx.workOrder.findFirst.mockResolvedValue({...job,updatedAt:new Date(version.getTime()+1)});await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ConflictException);});
});
