import { describe, expect, it, jest } from '@jest/globals';
import { ConflictException, ForbiddenException, NotFoundException } from '@nestjs/common';
import { WorkOrderStatus } from '@prisma/client';
import { TechnicianJobsService } from './technician-jobs.service';
const version = new Date('2026-08-17T08:00:00.000Z');
const operation = { operationId: '11111111-1111-4111-8111-111111111111', startedAt: '2026-08-17T08:05:00.000Z', expectedVersion: version.toISOString(), expectedScopeRevisionId: 'scope-1' };
const job:any = { id:'wo-1',reference:'WO-1',title:'Deep Cleaning',description:'Use eco products',status:WorkOrderStatus.ASSIGNED,scheduledAt:version,preferredTimeWindow:null,updatedAt:version,startedAt:null,startOperationId:null,startedScopeRevisionId:null,executionScopeRevisions:[{id:'scope-1',revision:1,additions:[],exclusions:[],createdAt:version,sections:[]}],jobLeaderId:'tech-1',service:{name:'Deep Cleaning',description:null},addOns:[],assignedTechnicians:[{technicianId:'tech-1',technician:{id:'tech-1',firstName:'Ada',lastName:'A'}}],property:{name:'Orange Farm',addressLine1:'1 Main',city:'Johannesburg'},accessInstructions:null,parkingInstructions:null,keyHandover:null,keyHandoverDetails:null,someonePresent:null,ecoFriendlyProducts:true,customerDeclaredExistingDamage:null};
function harness(record:any={technicianId:'tech-1'}) { const tx:any={workOrder:{findFirst:jest.fn(async()=>job),updateMany:jest.fn(async()=>({count:1}))},workOrderActivity:{create:jest.fn(async()=>({}))}}; const prisma:any={employeeRecord:{findFirst:jest.fn(async()=>record)},workOrder:{findMany:jest.fn(async()=>[job]),findFirst:jest.fn(async()=>job)},$transaction:jest.fn(async(cb:any)=>cb(tx))}; return {service:new TechnicianJobsService(prisma),prisma,tx}; }
describe('Technician assignment-scoped jobs',()=>{
 it('returns only the canonical Technician assignment query and a minimized DTO',async()=>{const {service,prisma}=harness();const result=await service.list('admin-tech','today');expect(prisma.workOrder.findMany).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({assignedTechnicians:{some:{technicianId:'tech-1'}}})}));expect(result.jobs[0]).not.toHaveProperty('customer');expect(result.jobs[0]).not.toHaveProperty('temporaryAccessCredentials');expect(result.jobs[0]).not.toHaveProperty('sourceQuote');});
 it('rejects ADMIN-only accounts without a linked active Technician',async()=>{const {service}=harness(null);await expect(service.list('admin','today')).rejects.toBeInstanceOf(ForbiddenException);});
 it('fails closed for guessed or removed assignments',async()=>{const {service,prisma}=harness();prisma.workOrder.findFirst.mockResolvedValue(null);await expect(service.brief('user','other-wo')).rejects.toBeInstanceOf(NotFoundException);});
 it('allows an assigned non-leader to view the brief but not start',async()=>{const {service,tx}=harness({technicianId:'tech-2'});const brief=await service.brief('user','wo-1');expect(brief.waitingForJobLeader).toBe(true);await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ForbiddenException);expect(tx.workOrderActivity.create).not.toHaveBeenCalled();});
 it('starts once with actual time, canonical ON_SITE lifecycle and one audit',async()=>{const {service,tx}=harness();await service.start('user','wo-1',operation);expect(tx.workOrder.updateMany).toHaveBeenCalledWith(expect.objectContaining({data:expect.objectContaining({startedAt:new Date(operation.startedAt),startedByTechnicianId:'tech-1',startOperationId:operation.operationId,status:WorkOrderStatus.ON_SITE})}));expect(tx.workOrderActivity.create).toHaveBeenCalledTimes(1);expect(tx.workOrderActivity.create).toHaveBeenCalledWith({data:expect.objectContaining({type:'JOB_STARTED',previousStatus:WorkOrderStatus.ASSIGNED,newStatus:WorkOrderStatus.ON_SITE})});expect(job.scheduledAt).toEqual(version);});
 it('reconciles the identical operation without another update or activity',async()=>{const {service,tx}=harness();tx.workOrder.findFirst.mockResolvedValue({...job,startedAt:new Date(operation.startedAt),startOperationId:operation.operationId,status:WorkOrderStatus.ON_SITE});await service.start('user','wo-1',operation);expect(tx.workOrder.updateMany).not.toHaveBeenCalled();expect(tx.workOrderActivity.create).not.toHaveBeenCalled();});
 it('rejects incompatible replay, cancellation and stale cached versions',async()=>{const {service,tx}=harness();tx.workOrder.findFirst.mockResolvedValue({...job,startedAt:new Date(),startOperationId:'22222222-2222-4222-8222-222222222222'});await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ConflictException);tx.workOrder.findFirst.mockResolvedValue({...job,status:WorkOrderStatus.CANCELLED});await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ConflictException);tx.workOrder.findFirst.mockResolvedValue({...job,updatedAt:new Date(version.getTime()+1)});await expect(service.start('user','wo-1',operation)).rejects.toBeInstanceOf(ConflictException);});
});

describe('Execution Evidence acknowledgement',()=>{
 const input={scopeRevisionId:'22222222-2222-4222-8222-222222222222',purpose:'REQUIRED_SECTION_EVIDENCE' as const,capturedAt:'2026-08-17T08:10:00.000Z',storagePath:'11111111-1111-4111-8111-111111111111/22222222-2222-4222-8222-222222222222/33333333-3333-4333-8333-333333333333/44444444-4444-4444-8444-444444444444.webp'};
 function evidenceHarness(section:any={id:'33333333-3333-4333-8333-333333333333'},existing:any=null,record:any={technicianId:'tech-1'}){const acknowledged={id:'server-evidence',localEvidenceId:'44444444-4444-4444-8444-444444444444',workOrderId:'11111111-1111-4111-8111-111111111111',scopeRevisionId:input.scopeRevisionId,sectionId:'33333333-3333-4333-8333-333333333333',technicianId:'tech-1',syncState:'SERVER_ACKNOWLEDGED'};const tx:any={executionSectionEvidence:{findUnique:jest.fn(async()=>existing),create:jest.fn(async()=>acknowledged),update:jest.fn(async()=>acknowledged)},workOrderExecutionSection:{findFirst:jest.fn(async()=>section)}};const prisma:any={employeeRecord:{findFirst:jest.fn(async()=>record)},$transaction:jest.fn(async(cb:any)=>cb(tx))};return{service:new TechnicianJobsService(prisma),tx,acknowledged}}
 it('acknowledges assigned Technician evidence for the exact active section',async()=>{const{service,tx}=evidenceHarness();const result=await service.acknowledgeEvidence('user','11111111-1111-4111-8111-111111111111','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444',input);expect(result.syncState).toBe('SERVER_ACKNOWLEDGED');expect(tx.workOrderExecutionSection.findFirst).toHaveBeenCalledWith(expect.objectContaining({where:expect.objectContaining({scopeRevisionId:input.scopeRevisionId})}))});
 it('rejects ADMIN-only identity and wrong work-order/scope/section context',async()=>{const admin=evidenceHarness(undefined,null,null);await expect(admin.service.acknowledgeEvidence('admin','11111111-1111-4111-8111-111111111111','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444',input)).rejects.toBeInstanceOf(ForbiddenException);const wrong=evidenceHarness(null);await expect(wrong.service.acknowledgeEvidence('user','11111111-1111-4111-8111-111111111111','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444',input)).rejects.toBeInstanceOf(NotFoundException)});
 it('returns the same authoritative evidence on retry without duplication',async()=>{const existing={id:'server-evidence',localEvidenceId:'44444444-4444-4444-8444-444444444444',workOrderId:'11111111-1111-4111-8111-111111111111',scopeRevisionId:input.scopeRevisionId,sectionId:'33333333-3333-4333-8333-333333333333',technicianId:'tech-1',syncState:'SERVER_ACKNOWLEDGED'};const{service,tx}=evidenceHarness(undefined,existing);const result=await service.acknowledgeEvidence('user','11111111-1111-4111-8111-111111111111','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444',input);expect(result).toBe(existing);expect(tx.executionSectionEvidence.create).not.toHaveBeenCalled();expect(tx.executionSectionEvidence.update).not.toHaveBeenCalled()});
});

describe('authoritative Complete Job',()=>{
 const input={operationId:'55555555-5555-4555-8555-555555555555',scopeRevisionId:'scope-1',fieldCompletedAt:'2026-08-17T09:00:00.000Z',expectedVersion:version.toISOString(),expectedStatus:'ON_SITE' as const};
 const section=(outcome:any='COMPLETED',evidence:any[]=[{localEvidenceId:'evidence',syncState:'CAPTURED_LOCAL'}],event:any={reason:null,note:null})=>({id:'section',title:'Bathroom',currentOutcome:outcome,evidencePolicy:'REQUIRED',evidence,currentOutcomeEvent:event});
 function completeHarness(overrides:any={}){const completionJob={status:WorkOrderStatus.ON_SITE,jobLeaderId:'tech-1',startedAt:version,startedScopeRevisionId:'scope-1',completionOperationId:null,executionScopeRevisions:[{sections:[section()]}],...overrides};const tx:any={workOrder:{findUnique:jest.fn(async()=>null),findFirst:jest.fn(async()=>completionJob),updateMany:jest.fn(async()=>({count:1}))},workOrderActivity:{create:jest.fn(async()=>({}))}};const prisma:any={employeeRecord:{findFirst:jest.fn(async()=>({technicianId:'tech-1'}))},$transaction:jest.fn(async(cb:any)=>cb(tx))};return{service:new TechnicianJobsService(prisma),tx};}
 it('allows only the assigned leader and accepts captured/pending-upload evidence',async()=>{const{service,tx}=completeHarness();await expect(service.complete('user','wo-1',input)).resolves.toMatchObject({status:WorkOrderStatus.COMPLETED,completionOperationId:input.operationId});expect(tx.workOrderActivity.create).toHaveBeenCalledTimes(1);const other=completeHarness({jobLeaderId:'tech-2'});await expect(other.service.complete('user','wo-1',input)).rejects.toBeInstanceOf(ForbiddenException);});
 it('blocks pending work, missing evidence and incomplete exception data',async()=>{for(const bad of [section('PENDING'),section('COMPLETED',[]),section('NOT_COMPLETED',[{}],{reason:null,note:null})]){const{service}=completeHarness({executionScopeRevisions:[{sections:[bad]}]});await expect(service.complete('user','wo-1',input)).rejects.toBeInstanceOf(ConflictException);}});
 it('returns the same operation without duplicate status or activity and rejects a different completion',async()=>{const{service,tx}=completeHarness();tx.workOrder.findUnique.mockResolvedValue({id:'wo-1',status:WorkOrderStatus.COMPLETED,completionOperationId:input.operationId,fieldCompletedAt:new Date(input.fieldCompletedAt),completionAcceptedAt:version});await service.complete('user','wo-1',input);expect(tx.workOrder.updateMany).not.toHaveBeenCalled();expect(tx.workOrderActivity.create).not.toHaveBeenCalled();const different=completeHarness({status:WorkOrderStatus.COMPLETED,completionOperationId:'66666666-6666-4666-8666-666666666666'});await expect(different.service.complete('user','wo-1',input)).rejects.toBeInstanceOf(ConflictException);});
});
